### ISSUE TITLE
Can it create shortcuts like AppLocale? / 能否支持创建快捷方式？

### ISSUE THREAD

**Issue by Aster37a** [xupefei/Locale-Emulator#100]
(Chinese translation follows/中文见后)
I have just installed this program in replacement of Applocale which fails to operate under Windows 10.
It's working perfectly fine at least with my current programs, and I sincerely thank the developer for that.
But just out of curiosity, is it possible to create shortcuts that will allow a program to be ran in Locale Emulator (like what AppLocale used to provide) instead of opening the target program folder every time and right-click on the .exe file? I think I may manually create a shortcut if I know how to use this program in the command line.
Thank you for your response in advance.

因为升级Windows 10之后Applocale不能用了，所以刚安装了这个软件作为替代，目前为止没有任何问题，谢谢开发者。
不过我就是好奇，这个程序能否支持创建目标程序的快捷方式，使得可以直接通过快捷方式加载运行目标程序（就像AppLocale那样），而不是每次都要手动打开目标程序文件夹用右键运行？或者如果谁能告诉我如何用命令行加载目标程序，我也可以试着自己做一个快捷方式。
提前谢谢各位。

**Comment by lialosiu** [comment]
右键的时候不是有个打开设置么，里面有创建快捷方式的啊
2015年8月2日 19:31于 "Aster37a" <notifications@github.com>写道：

**Comment by Aster37a** [comment]
哈哈哈真的耶…我下午在主程序里面研究了半天都没发现这个功能于是费了半天劲发贴来求助 = =
谢谢你的神速回答 ^^


2015-08-02 20:34 GMT+09:00 Lialosiu <notifications@github.com>:
