### ISSUE TITLE
可否在區域後標註區碼名稱

### ISSUE THREAD

**Issue by ForeverIndex** [xupefei/Locale-Emulator#103]
舉個例子：GB2312
Locale-Emulator： http://i.imgur.com/y7c12EX.png
NTLEA : http://i.imgur.com/bBBCO8m.png

恕小人不才，Locale-Emulator裡哪一個區域是GBK呢...

**Comment by xupefei** [comment]
抱歉，这个无法做到。你可以记忆一下常用编码，比如 GBK 就是简体中文，BIG5 是繁体中文，S-JIS 是日语等等。
