### ISSUE TITLE
i18n for project web page?

### ISSUE THREAD

**Issue by KagamiChan** [xupefei/Locale-Emulator#111]
@xupefei Since the project homepage is moved to github pages, maybe we can make an i18n version covering as many languages as the software itself?

**Comment by xupefei** [comment]
I don't think it's necessary. Chinese and English is enough for most people to know this software. Another reason is we don't have this much of translators.

**Comment by KagamiChan** [comment]
So If I push my French translation of gh-pages, will you accept it? :)
If so, The current language indicator may need some modification.
Hopefully there won't be frequent updates on these web pages, same as the translation for the program

**Comment by xupefei** [comment]
Sure :)

I think we can use Javascript to detect the user's language and jump to the
corresponding version.

**Comment by xupefei** [comment]
Hello, I have updated the webpage for auto detecting user's language.
You can create a pull request that contains the translated version of https://github.com/xupefei/Locale-Emulator/blob/gh-pages/locales/en/translation.json.

**Comment by KagamiChan** [comment]
@xupefei Thanks for hard working. There's one issue concerning browser language detection. 
There're 2 APIs doing the job: [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) and [`navigator-languages`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language), the latter one is onlysupported by Chrome and Firefox.
`navigator-languages` resturn a list of languages according to user preference and can differ from the interface language. For example, if I set `en-US` my preference language in my Chinese interface Chrome, `navigator.language` always returns `"zh-CN'` but `navigator-languages` returns `en-US` as the first element.

**Comment by KagamiChan** [comment]
btw, I think I can add the detection tonight along with my translations

**Comment by xupefei** [comment]
I think the MDN is wrong. As I tested, both Chrome and Firefox return the first element in accept-language list when calling `navigator.language`.

**Comment by KagamiChan** [comment]
What I described is a little different. In chrome you can arrange your language preference in chrome://settings/languages, `navigator.languages` will be the same list as in your language pref, but `navigator.language` will return zh-CN.
In FF `navigator.languages` works alike, and `navigator.language` return the first element in the lang. pref.
My Chrome version is 45 and FF 42.

**Comment by xupefei** [comment]
Okay let's just keep using this easy solution. I think most people have the same setting on both UI language and accept-languages.

**Comment by KagamiChan** [comment]
```
    if(typeof navigator.languages === 'undefined'){
        lng = navigator.language
    }
    else{
        lng = navigator.languages[0]
    }
```
That's my idea. Anyway, i18n is just a surprise.

**Comment by xupefei** [comment]
Thanks, but I don't want to use such complex logic. Keep it simple :)
