### ISSUE TITLE
High DPI Awareness

### ISSUE THREAD

**Issue by MainVirtualizer** [xupefei/Locale-Emulator#117]
I set __COMPAT_LAYER so that HighDpiAware  is globally turned on for all apps. In 2.0.0.2, every works well, but after I upgrade it to 2.0.1.0, Windows' DPI emulation kicks in and I have to manually set HighDpiAware for each program. Hope future version of LE can add options about High DPI.

**Comment by xupefei** [comment]
LEGUI already have High DPI support. LEInstaller have no such support, but
used only once only when installing/upgrading.
LEproc and LEupdater have no GUI at all.

What do you think we should improve?

**Comment by Grenaid** [comment]
The problem seems to be when LEGUI runs the program.  Even if "Disable display scaling" is set with windows for the executable I want to run (and set for LEGUI.exe as well) somehow when the game runs scaling is still messed up (the mouse looks like it is in another place than where it is.)

**Comment by xupefei** [comment]
Thanks for the message. This issue will be resolved in the next release.
If you want to try it now, please check out the source code and compile it.
