### ISSUE TITLE
Font in applications

### ISSUE THREAD

**Issue by DarkTl** [xupefei/Locale-Emulator#118]
I'm not sure if you even support modified applications, but I want to tell about some issues with fonts. I'm talking about Artificial Academy 2 character editor modified by hongfire team, ie translated. It still cannot work properly without locale change though.
One screenshot was made with emulator, another one with locale.
![1](https://cloud.githubusercontent.com/assets/4967371/9699327/ec5e653e-53ef-11e5-87f0-265f71950dfd.jpg)
![2](https://cloud.githubusercontent.com/assets/4967371/9699328/f228da4e-53ef-11e5-9436-a84a4a551311.jpg)

As you see, if you run it via locale emulator, the application for some reason uses another font which is too large and bold . As a result, text is too large for buttons.

**Comment by xupefei** [comment]
That is because the translators didn't specify the font. I can do nothing, sorry :(
