### ISSUE TITLE
Locale emulator have problem with willplus game in win10

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#125]
text box, backlog, setting doesn't get any text.
I think it might be related with font or locale issue.

this is example image used
見上げてごらん、夜空の星を　体験版.
[Imgur](http://i.imgur.com/b8NZmWi.png)
[Imgur](http://i.imgur.com/ieZYb5C.png)
(displayed text is image)

**Comment by xupefei** [comment]
Please read the last comment on #80.

**Comment by mireado** [comment]
god... Thank you for kind answer >_<
