### ISSUE TITLE
Win10_64位系统运行有BUG

### ISSUE THREAD

**Issue by wyl221** [xupefei/Locale-Emulator#126]
用最新的2.0.1.0玩戦女神VERITA2.0，只要一打开游戏，开始菜单和系统音量调节就没反映了。系统日志里有：激活应用 Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy!App 失败。的日志。系统已升级到最新版。望修复。

**Comment by xupefei** [comment]
​这个不怪我……​

2015-10-20 22:02 GMT+08:00 wyl221 <notifications@github.com>:
