### ISSUE TITLE
Not sure if bug: Context menu not appearing for all file types

### ISSUE THREAD

**Issue by reyaz006** [xupefei/Locale-Emulator#129]
I saw that shell extension gets asked to be installed for all file types [here](https://github.com/xupefei/Locale-Emulator/blob/4f81f08048e1556b42ee389a9940275ce78840cb/LEContextMenuHandler/FileContextMenuExt.cs#L243):
<code>ShellExtReg.RegisterShellExtContextMenuHandler(t.GUID, "*", "LocaleEmulator.LEContextMenuHandler Class");</code>

However, on my system (8.1 x64), I can only see it on certain file types - .exe, .lnk, .txt, .mp4 etc. I don't see the menu item on images and archives. Is this intended? Can someone confirm this?

Personally, I have no problems with how it works now - I mostly use locale emulation on .exe and .txt anyway.

**Comment by xupefei** [comment]
It is depend on whether its associated application is a 32-bit one.
For exmaple, in `%WINDIR%\SysWOW64` there is a 32-bit `notepad.exe`, so LE shows menu on all txt files.
So If your image viewer is 32-bit, you will see LE menu.
