### ISSUE TITLE
使用 "ie9字體喧染" 會導致Locale-Emulator失效

### ISSUE THREAD

**Issue by fb70480** [xupefei/Locale-Emulator#130]
win10 64bit

我有使用EZGDI v6(系統字體喧染)，使用其中的ie9喧染會導致Locale-Emulator失效

![default](https://cloud.githubusercontent.com/assets/15393669/10837568/e08c8994-7ef5-11e5-966e-dbc8540a52f8.jpg)

**Comment by xupefei** [comment]
抱歉，这个问题无法解决。还请在 EzGDI 中添加排除程序。
