### ISSUE TITLE
关于运行参数的问题

### ISSUE THREAD

**Issue by tianlong20018** [xupefei/Locale-Emulator#131]
因为工作需要 经常需要需要在日文系统跟中文系统之间切来切去 自从发现了Locale Emulator 简直赞爆了

有一个问题想请教下 现在在使用的日文软件中有一款cad的外挂软件 需要在autocad的后面增加运行参数且要在管理员权限下才能运行。

"D:\Program Files (x86)\AutoCAD 2008\acad.exe" tatsu /c D:\Program Files (x86)\SHIDAI\TATSU /p "D:\Program Files (x86)\SHIDAI\TATSU\TATSU.arg" /t acad /b menu.scr

直接运行参数里面填写 还是会加载失败。

系统win10 64位 专业版 界面是中文的 修改地区跟非unicode语言 为日本 日文软件运行都正常 通过Locale Emulator  运行中文软件也正常

修改地区跟非unicode语言 为中国后 日文软件不需要运行参数通过Locale-Emulator也可以正常运行

**Comment by tianlong20018** [comment]
![qq 20151031095939](https://cloud.githubusercontent.com/assets/15333940/10861389/462a0cbe-7fb8-11e5-8667-e460cfd745b8.jpg)

**Comment by xupefei** [comment]
你的步骤和下面的一样么？

1. 在 `"D:\Program Files (x86)\AutoCAD 2008\acad.exe"` 上右键，LE -> 修改此程序配置。
2. 在参数中输入 `tatsu /c D:\Program Files (x86)\SHIDAI\TATSU /p "D:\Program Files (x86)\SHIDAI\TATSU\TATSU.arg" /t acad /b menu.scr`。
3. 点击 保存 或 建立快捷方式。
4. （4，5 二选一）在 `"D:\Program Files (x86)\AutoCAD 2008\acad.exe"` 上右键，LE -> 以此程序配置执行。
5. （4，5 二选一）双击桌面上的快捷方式。

**Comment by tianlong20018** [comment]
应该是因为  起始位置  的问题

切换到日文状态下 把原来的快捷方式 清空起始位置以后 也会出错

![qq 20151031113817](https://cloud.githubusercontent.com/assets/15333940/10861686/792ca890-7fc4-11e5-9b68-b348ec554c2b.jpg)

**Comment by xupefei** [comment]
把`menu.scr`改成绝对路径，别忘了加引号。

**Comment by tianlong20018** [comment]
好的 我周一试试看

**Comment by xupefei** [comment]
最新的LE解决了这个问题。详情可以看看日志。
