### ISSUE TITLE
Not work with Fallout 2 Big5 version

### ISSUE THREAD

**Issue by samuelchen** [xupefei/Locale-Emulator#135]
On window 10 64bit, It works well with Baldur Gate 2 Big5 (zh-HK).

But it does not work with Fallout 2 Traditional Chinese version. 
Neither work with zh-HK nor zh-TW. Game can be started, but text are disappeared.

**Comment by xupefei** [comment]
Locale Emulator is designed for running AVG games, and Fallout is not an AVG.
BTW, as I remember Fallout 2 has no official Chinese version.
