### ISSUE TITLE
font(?) or text broken issue.

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#137]
font(?) or text broken issue.

it occur on 
元ヤンの奥さんは好きですか？～強気な人妻さんとエッチで勝負！ セクシー妻もいるよ～
![Imgur](http://i.imgur.com/O6aemc4.jpg)

ntleas display font well, while save/load doesn't works.

And same issue on win10, あの晴れわたる空より高く

Locale emulator have broken text.
![Imgur](http://i.imgur.com/IXGea5e.png)

but, ntleas have not broken text.
![Imgur](http://i.imgur.com/CUiCEsh.png)

**Comment by xupefei** [comment]
Please try installing the "Japanese Supplemental Fonts" font. Guide here:
http://www.tenforums.com/tutorials/7565-optional-features-manage-windows-10-a.html

**Comment by try080** [comment]
2nd this issue on other 平安亭 titles. I've tried using both check and uncheck on 'run as admin' and 'registry redirection' options
Here's the list of games I've tried it on:
1. 友達のお母さんは好きですか？～息子の友人にハマったオバちゃん妻～
2. 平凡な奥さんは好きですか？～真面目な主婦をエッチ漬けにしちゃおう！～
3. カノジョのお母さんは好きですか？～クールな人妻社長を籠絡せよ！～
4. ナースの奥さんは好きですか？～世話焼きオバちゃん陥落～

I'm using Win10 x64 with Japanese Supplemental Fonts and Locale-Emulator 2.1.0.0.
 
NTLEA displayed the text properly and like the OP said no save/load function as the game would immediately crash. 
One thing that I noticed that whilst Locale-Emulator perfectly display the game title (title bar) like OP showed, NTLEA was gibberish. This is the example on ナースの奥さんは好きですか？with NTLEA
![test](https://cloud.githubusercontent.com/assets/6310086/11679534/50449602-9e84-11e5-99e8-efea82c39296.png)

**Comment by xupefei** [comment]
OK, I remembered the last time when I analyzing 平安亭 games when I found a they use a special windows API for decryption. A special parameter in "registry redirection" can fxck that API, but as in the feedback there is many people saying they can't open FileOpenDialog and FileSaveDialog, [I decide to disable](https://github.com/xupefei/Locale-Emulator/commit/6bfde7c624d225d99a2e810834825e0a3e41d481) it for better compatibility.

The solution is:

1. Run regedit.
2. Modify values for keys in Line 16 and 19.

Then you can try that game again.

**Comment by try080** [comment]
The advice solved the problem! Thank you very much!

For those who are not familiar with these stuffs, please backup regedit (and system if you must).
