### ISSUE TITLE
This broke my start menu in WIndows 10

### ISSUE THREAD

**Issue by Disastorm** [xupefei/Locale-Emulator#138]
After installing this my start menu no longer worked in Windows 10.
After uninstalling it my start menu was still not fixed.
Not sure how to fix my start menu now, might have to re-install Windows...

Windows 10 Pro x64.

**Comment by xupefei** [comment]
I am not sure either, but it can be sure that your issue is not related to
LE.

**Comment by Disastorm** [comment]
Well I got my start menu back by re-installing the Windows 10 default apps 
( Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} )

However, this most definitely occured immediately after installing the Locale-Emulator.

**Comment by xupefei** [comment]
I think your start menu is already broken before the installation. Perhaps you can notice the broken after any operation, eg. reboot, install another program.
