### ISSUE TITLE
Locale-Emulator italian translation

### ISSUE THREAD

**Issue by JamesMaloney** [xupefei/Locale-Emulator#141]
Don't know if I'm writing in the right section, I'm sorry if not.
As for title, I've translated Locale-Emulator in italian and I'll link here the translations so you can add them in your next update, if you want.
Thank you for your attention and have a nice day!

P.S. I had to add .txt extension at the end of both files for uploading, just rename it again...
[it-IT.xaml.txt](https://github.com/xupefei/Locale-Emulator/files/44439/it-IT.xaml.txt)
[it-IT.xml.txt](https://github.com/xupefei/Locale-Emulator/files/44440/it-IT.xml.txt)

**Comment by xupefei** [comment]
Thank you very much!
