### ISSUE TITLE
LE对x64程序的兼容性存在问题

### ISSUE THREAD

**Issue by df32** [xupefei/Locale-Emulator#142]
在Win10 x64系统下，安装LE后，只有x32程序的右键菜单会显示LE菜单，x64不会显示。
且LE似乎并不能支持x64位程序的运行。

* 下面的命令能够用记事本打开txt文档，但进程是x32位的

> ./LEProc.exe -runas 211352eb-af7f-4c41-ae84-29aa4e8c8c2c "D:\Downloads\readme.txt"

* 将zip文档默认打开方式设置为x64的WinRAR，下面的命令不会使WinRAR运行

> ./LEProc.exe -runas 211352eb-af7f-4c41-ae84-29aa4e8c8c2c "D:\Downloads\era0001734.zip"

* 在WinRAR.exe.le.config都设置了地区设置的情况下（尽管GUID不同），x32位的WinRAR成功的应用了地区设置，而x64仍然使用的是系统默认地区设置

> ./LEProc.exe -run "D:\Program Files (x86)\WinRAR\WinRAR.exe"

> ./LEProc.exe -run "D:\Program Files\WinRAR\WinRAR.exe"

![winrar](https://cloud.githubusercontent.com/assets/9204710/11434378/6a997c8e-9506-11e5-98e9-0733d1c21da4.jpg)
左 - WinRAR(x32)；右 - WinRAR(x64)

最后问一下，如果我要在注册表中，设置某一种文件以LE配置的非默认打开程序来执行文件，应该怎样设计注册表。
例如.zip默认打开方式为资源管理器，我想用LE配置的WinRAR打开文件

**Comment by xupefei** [comment]
目前 LE 并不支持 64 位程序。



> 如果我要在注册表中，设置某一种文件以LE配置的非默认打开程序来执行文件，应该怎样设计注册表

目前只有在 WinRAR.exe.le.config 中写明运行参数这一种办法。以后我会让 LEProc支持 LeProc.exe -run
WinRAR.exe *arguments_here* 这种用法，但现在我并没有太多的时间，抱歉。当然，如果你有能力的话，自己改一下代码也是不难的。

2015-11-27 13:02 GMT+08:00 风飏 <notifications@github.com>:

**Comment by xupefei** [comment]
另外，我推荐你使用自带编码转换的 Bandizip <http://www.bandisoft.com/bandizip/>。

2015-11-27 13:17 GMT+08:00 Paddy Xu <xupaddy@gmail.com>:

**Comment by df32** [comment]
原来如此。
十分感谢你推荐的压缩程序。
