### ISSUE TITLE
Launch Failed.

### ISSUE THREAD

**Issue by sthts112** [xupefei/Locale-Emulator#143]
Locale.Emulator.Version1.0.9.1

win7 32bit home premium

Launch failed.

Commands: "path*&^* anyway"

Error Number: C0000001

Administrator: True

If you have any antivirus software running, please turn it off and try again.

If you think this error is related to LE itself, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

I've turned off all anti-virus software and tried again but still error.  also i was formet [C drive , system] then i'm never installing anti-virus software but until now error

now what can i do?

**Comment by xupefei** [comment]
I suggest you switch to another software, e.g. [NTLEAS](https://ntlea.codeplex.com/).

Locale Emulator has stopped further support for your OS. See [this post](https://github.com/xupefei/Locale-Emulator/wiki/Stopping-support-for-old-Windows-OS) for details.
