### ISSUE TITLE
在运行台服冒险岛时被反外挂软件强行停止

### ISSUE THREAD

**Issue by a554233472** [xupefei/Locale-Emulator#147]
用LE转码台服冒险岛（枫之谷，即Maplestory）时被反外挂软件检测，强行使游戏停止运行，反外挂软件为XIGNCODE，错误代码是0xE019100B，以下是XIGNCODE官方回复

您好，
这里是wellbia.com反外挂服务支援组。
非常抱歉对您游戏带来的不便。
您游戏发生错误的原因是因您在游戏中运行了与游戏无关的程式发生游戏强行终止的问题。

D:\Program Files\Locale Emulator\LocaleEmulator.dll

请删除或关闭此路径的未知程式后重新启动游戏。
而且请使用最新版本的杀毒软体检查您的电脑。

谢谢。

**Comment by xupefei** [comment]
抱歉，无能为力。

**Comment by ganwen1994** [comment]
已經給保護公司發去了郵件,等消息吧.
