### ISSUE TITLE
VOICEROID  Ex

### ISSUE THREAD

**Issue by shonferg** [xupefei/Locale-Emulator#149]
When I try to run VOICEROID+ Ex in an English version of Windows 10, I get this message:

![voiceroid error](https://cloud.githubusercontent.com/assets/10731230/11886096/3f7ec60a-a4f4-11e5-8757-a72939fe406f.png)

I get this message and the application shuts down.

If I change the UI Language of Windows itself to be in Japanese, and change all locale settings to Japan, then I can run the application normally, even without using Locale Emulator.

I think the application is checking the UI language of windows instead of checking the locale.

**Comment by xupefei** [comment]
Hey, please try the solution here: https://github.com/xupefei/Locale-Emulator/issues/137#issuecomment-163154118.

**Comment by shonferg** [comment]
It worked!  Thank you!

**Comment by shonferg** [comment]
On second thought, it does let me open the program, but now various Windows menus are showing in Japanese instead of English.  Do I need to switch it back and forth whenever I want to start this application?

**Comment by xupefei** [comment]
Yes, you have to do this now. In future I will add a new option that can
solve this issue.

**Comment by shonferg** [comment]
Awesome, thank you so much!  I appreciate all the work you've put into this program, it is very useful!
