### ISSUE TITLE
有些exe檔案右鍵選單沒有Locale Emulator的選單

### ISSUE THREAD

**Issue by tredgdhesc** [xupefei/Locale-Emulator#150]
有些exe檔案右鍵選單沒有Locale Emulator可使用
像是7-Zip的7zFM.exe的右鍵選單就沒有
用的系統是win 10
版本是Locale.Emulator.2.1.0.0

**Comment by xupefei** [comment]
你用的 7z 是 64位的吧。LE 不支持 64 位程序：https://github.com/xupefei/Locale-Emulator/issues/142
