### ISSUE TITLE
VOICEROID+ 无法绕过区域限制

### ISSUE THREAD

**Issue by amarillonmc** [xupefei/Locale-Emulator#151]
如题，使用软件
VOICEROID+ 水奈瀬コウ EX
VOICEROID＋ 琴葉葵
VOICEROID＋ 琴葉茜
使用上下文菜单转区后，仍旧出现“只能在日本语环境下”运行的警告信息，无法打开。

环境是Windows 10。

**Comment by xupefei** [comment]
提问前请搜索：https://github.com/xupefei/Locale-Emulator/issues/149

**Comment by amarillonmc** [comment]
The problem is, I already tried setting PreferredUILanguages and MachinePreferredUILanguages, however, the later keep reverting into en-US, thus this fix would never work.

Currently I'm downloading the Japanese UI Language Pack through Control Panel (so I can set UI language as Japanese and hopefully get it working). however I feel that shouldn't been the solution since we use Locale Emulator for exactly the purpose of NOT doing that.

**Comment by xupefei** [comment]
Currently the solution is compiling a LECommonLibrary.dll by your self:

1. Modify the contents of https://github.com/xupefei/Locale-Emulator/blob/master/LECommonLibrary/Resources/LERegistry.xml to https://github.com/xupefei/Locale-Emulator/blob/e0b1341075a6364933650cb6f40c11ce78699541/LEProc/LERegistry.xml
2. Remove the comment symbol at Line 18 and 25
3. Complie

As I said in previous issue I will add a option for enabling/disabling these two items. But now the only solution is in above.

**Comment by xupefei** [comment]
This issue should be fixed in the recent version.
Please leave a message after you tried it.

**Comment by shonferg** [comment]
Works for me!  Thank you!
