### ISSUE TITLE
Steam Overlay

### ISSUE THREAD

**Issue by Kumichan** [xupefei/Locale-Emulator#153]
Was wondering is there anyways to make this work with steam overlay. Everytime i try and run Touhou Puppet Play Performance i get this:
---------------------------
Locale Emulator Version 2.1.0.0
---------------------------
Error Number: 0

Commands: SYSTEM_REPORT

Microsoft Windows NT 10.0.10586.0 x64

NTDLL.DLL: 10.0.10586.20

KERNELBASE.DLL: 10.0.10586.0

KERNEL32.DLL: 10.0.10586.0

USER32.DLL: 10.0.10586.20

GDI32.DLL: 10.0.10586.0

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
OK   
---------------------------

Is there anyway around this without me having to change my whole pc to japanese. Wanted to use steam overlay for screenshots and streaming to friends without the hassle of getting an external streaming program/ taking the screenshots and placeing themand ect ect

**Comment by xupefei** [comment]
I doubt the message is not related to Steam. Double click on LEProc. exe
will product the same texts.

**Comment by Kumichan** [comment]
Ah i see. Well is there a way around this or do i have to change my system locale?

**Comment by xupefei** [comment]
Try run Steam with Locale Emulator.

**Comment by Kumichan** [comment]
I tried but i dont eve i n get an option to use it with steam and when i try and drag it over it all i get is a red circle.

**Comment by xupefei** [comment]
Is there no LE menu when you right click on steam.exe?
Steam is a 32bit app so there should have a LE menu item.

**Comment by Kumichan** [comment]
Nothing at all when i click on steam.

**Comment by xupefei** [comment]
Are you sure?

![image](https://cloud.githubusercontent.com/assets/1687847/12060670/c7603426-afaf-11e5-80bd-c8c5254a1b94.png)

**Comment by Kumichan** [comment]
My bad on this one i was doing it form a shortcut instead of the exe. everything workin now :)
