### ISSUE TITLE
关于LE的BUG

### ISSUE THREAD

**Issue by 1262917464** [xupefei/Locale-Emulator#156]
使用LE日文启动RPG Maker 2000/2003 RTP的安装文件时
LE日文启动后的第一个程序是成功的，但是第二个不成功
RPG Maker 2000/2003 RTP：http://pan.baidu.com/s/1kTXwRx9

**Comment by xupefei** [comment]
右键选那个 as admin 的配置。

**Comment by 1262917464** [comment]
不行啊，已经尝试过了
