### ISSUE TITLE
Locale Emulator russian translation

### ISSUE THREAD

**Issue by TokcDK** [xupefei/Locale-Emulator#158]
Hi, here is russian translation files for the Locale Emulator:
[RU4LE.zip](https://github.com/xupefei/Locale-Emulator/files/91592/RU4LE.zip)

Thank you for this very good tool!

**Comment by xupefei** [comment]
![8z1eegu](https://cloud.githubusercontent.com/assets/1687847/12349963/a10a592c-bbae-11e5-9655-34a2cfdb1330.png)
