### ISSUE TITLE
Brazilian Portuguese(pt-BR) translation

### ISSUE THREAD

**Issue by axellslade** [xupefei/Locale-Emulator#160]
There you go!

Cheers,
[pt-BR.zip](https://github.com/xupefei/Locale-Emulator/files/92989/pt-BR.zip)

**Comment by axellslade** [comment]
And by the way, there's a string that can't be translated:
"No profile, please run LEGUI.exe"
"Sem perfil, por favor execute LEGUI.exe" 
which shows when there are no profiles set in the program.

**Comment by xupefei** [comment]
Thank you very much.
Because the translation is maintained by many different translators, I don't want to add more translation that may become a trouble with job synchronization.
