### ISSUE TITLE
Maji de Watashi ni Koi Shinasai! errors

### ISSUE THREAD

**Issue by Fowz** [xupefei/Locale-Emulator#164]
Well I updated recently to Windows10 then I got the error where AppLocale wasn't working anymore then I found this program.

But the thing is as I was trying to play Majikoi the font was with a bad kerning and the game is skipping everything automatically.
![160118 1849](https://cloud.githubusercontent.com/assets/10855150/12402470/68592a1e-be14-11e5-8ac9-abb8a12decf4.png)

So do anyone have found the solution for this problem? Thanks in advance.

**Comment by xupefei** [comment]
It look not like MS Gothic, but Tahoma.
Are you sure you have MS Gothic font installed?

**Comment by Fowz** [comment]
Thanks, it was the font that was not installed.
And for the autoskip it was a conflict with my joystick, damn they could fix W10 drivers soon.
