### ISSUE TITLE
Debugger detected. close debugger and try again..

### ISSUE THREAD

**Issue by Segaco1** [xupefei/Locale-Emulator#168]
So, I installed Locale Emulator because I was too lazy to change my region to japanese.

The thing is, I tried to open a game called Chaos Head with locale emulator, and it didn't work, this message popped instead:

"Debugger detected. close debugger and try again..."

It used to work before (the game), well, it used crash after clicking "start game", but it's something.

And now I uninstalled Locale Emulator, and it keeps happening, help :l

**Comment by xupefei** [comment]
Debugger can be many things, like your antivirus software, your system
enhancement app, etc. You should check what application you have installed,
(maybe) uninstall one by one and try again.
