### ISSUE TITLE
Option suggestion : generate shortcut whenever using profile

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#170]
How about add auto generate shortcut option whenever using profile?

we can generate shortcut by two click.
but i think Locale Emulator can make it by just one click(profile that include shortcut generating setting).

I'm sorry to have bothered you.
this is just suggestion.
if you don't like it. please skip this issue >_<

**Comment by xupefei** [comment]
Could you explain (in detail) your idea?

**Comment by mireado** [comment]
![Imgur](http://i.imgur.com/NhduZev.png)
how about add new option to global profile?(red box area)
and then when using global profile on context menu.

**Comment by xupefei** [comment]
You mean every time when using this profile, a shortcut will be created on the Desktop?

**Comment by mireado** [comment]
Yes. I mean that.
maybe it could be useless,
but I think it could be a small help.

**Comment by xupefei** [comment]
Sorry, I think it is not useful for lots of users, but will cause a huge trouble in translation update. I want to avoid modifying language files as much as possible.
PS, I suggest you to try this: https://leshortcut.codeplex.com/
