### ISSUE TITLE
[BUG]LEConfig contain no info

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#172]
some time after using locale emulator,
LEConfig tend to have no infomation.
![Imgur](http://i.imgur.com/yrDRFPm.png)
![Imgur](http://i.imgur.com/xKfZE2H.png)

so, sometime need to re-make setting that already made..

**Comment by xupefei** [comment]
Try move LE to another location, e.g. your desktop because this may cause by permission issue.

**Comment by mireado** [comment]
Thank you for kind answer >_<
