### ISSUE TITLE
有没有可能设置区域为UTF-8？

### ISSUE THREAD

**Issue by Komeiji-Kuro** [xupefei/Locale-Emulator#174]
抱歉打扰了。可能提了一个不是Bug的问题。
是这样的，有一个程序（文明V的SDK，运行环境Windows 10），对于中文的内容，显示的为乱码。
然后我试着使用了各种Locale，都失败了。
然后我分析了乱码的内容，发现是原本应该显示为UTF-8的内容，显示为了本地编码GBK。
那么，有没有可能，使得Locale为UTF-8呢？
如果可能话，可以通过简单修改LE的源码做到吗？

**Comment by xupefei** [comment]
我觉得修改文明 5 SDK 更简单……

2016-01-29 17:51 GMT+08:00 Komeiji Kuro <notifications@github.com>:

**Comment by Komeiji-Kuro** [comment]
但是不会逆向啊（哭），LE或者AppLocale的实现是建立在Windows内置功能上吗？还是说有自己的一套转换显示的方式？

**Comment by xupefei** [comment]
不是内置功能。
你可以找个懂逆向的人改改文明 SDK，LE 这边无能为力。
