### ISSUE TITLE
seems to doesn't works windows 10 redstone

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#176]
![Imgur](http://i.imgur.com/bcJMDOj.png)
![Imgur](http://i.imgur.com/R3G793X.png)
(windows 10 Insider Preview Build 14251_rs1, x86)
(windows 10 Insider Preview Build 14257_rs1, x86)
Locale-Emulator v2.2.0.0.pre2

but, seems to works well with ntleas046.
![Imgur](http://i.imgur.com/Ob8k6DT.png)

**Comment by xupefei** [comment]
We will see after it is stable.
