### ISSUE TITLE
Install to program files?

### ISSUE THREAD

**Issue by llakssz** [xupefei/Locale-Emulator#179]
Basically all installed programs install to Program Files, it would be nice if your installer did this.
This program is not really 'portable' (it needs to be 'installed' and attach to the context menu) - so why not install to a constant directory?
I think this is a cleaner solution than making the user chose themselves, but of course, most programs let you pick the install directory also.

Thanks for all the work, it's a great help on Windows 10! :)

**Comment by xupefei** [comment]
Install to Program Files may cause some permission issue: the LEConfig.xml will be protected by UAC. So every time you want to modify sth. you will need admin permission.

**Comment by llakssz** [comment]
Ah, I assumed applications would be able to write to their own config files without UAC prompts.
What about storing in the userdata folder?

Just an idea.
Thanks again!

**Comment by xupefei** [comment]
​Hi,

That will be a trouble for those who want to remove/backup LE or copy LE to
another device which will leave trash files behind. I also have a plan
about portable installation (LEInstaller does not require admin at all).

**Comment by llakssz** [comment]
Cool, good luck with the development!
