### ISSUE TITLE
在Win10下打开游戏时KiriKiri引擎诡异报错

### ISSUE THREAD

**Issue by Aernil** [xupefei/Locale-Emulator#180]
Win10 x64简体中文版系统
游戏本身(kirikiri)如果不用换区软件是可以正常运行的，当然有乱码
想用LE试着打开游戏，第一次成功打开了而且没有乱码，也不会卡死，但是从第二次开始就出现
「プラグイン　LayerExImage.dll を読み込るめません」 的提示
重新安装游戏，单独覆盖LayerExImage.dll，重装LE，清进程重启都没有用

/ LEProc运行结果
---------------------------
Locale Emulator Version 2.2.0.0
---------------------------
Error Number: 0

Commands: SYSTEM_REPORT

Microsoft Windows NT 10.0.10240.0 x64

NTDLL.DLL: 10.0.10240.16683

KERNELBASE.DLL: 10.0.10240.16683

KERNEL32.DLL: 10.0.10240.16384

USER32.DLL: 10.0.10240.16603

GDI32.DLL: 10.0.10240.16644

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

**Comment by xupefei** [comment]
开启伪造 UI 语言了吗？

**Comment by Aernil** [comment]
是的，开启了，需要关闭吗？
如果是的话在什么情况下要重新开启？

Paddy Xu <notifications@github.com>于2016年2月23日周二 19:19写道：

**Comment by xupefei** [comment]
运行某些游戏才需要开启，例如 TinkleBell 家的。
在有些环境下开启此选项会出现 DLL 加载失败 bug，原因未知。

**Comment by Aernil** [comment]
关闭后确实恢复正常，多谢

Paddy Xu <notifications@github.com>于2016年2月23日周二 20:55写道：
