### ISSUE TITLE
Auto-Update 自動更新

### ISSUE THREAD

**Issue by m31317015** [xupefei/Locale-Emulator#182]
沒事做, 中英文對照. :P
Got nothing to do, typed both Chinese and English. :P

某程度上, LE更新起來挺麻煩的, 能弄個自動更新功能嗎?
Somehow updating LE is pretty annoying, can you make an Auto-Update feature?

**Comment by xupefei** [comment]
Currently the auto-update is just by copying & overwriting files, run Installer, click Update. I don't think it is such complex...

**Comment by m31317015** [comment]
So you mean the installer is the updater? I'm so stupid that I downloaded the file and the run the installer after I placed those new files. :laughing:
