### ISSUE TITLE
液魂研究会 - ないしょのお医者さんごっこ crash without any message

### ISSUE THREAD

**Issue by xd79077921** [xupefei/Locale-Emulator#183]
System type: Windows 10 64bit Build 10586.104
Name and company of the broken application: 液魂研究会 - ないしょのお医者さんごっこ
http://www.dlsite.com/maniax/work/=/product_id/RJ144879.html
No error message. Only dmp: ないしょのお医者さんごっこ.1D16C199F329DC1.crash.dmp

**Comment by xd79077921** [comment]
Yes, 2.2.0.0.pre2
I follow this thread install Japanese fonts but still not working: https://github.com/xupefei/Locale-Emulator/issues/80
Many game in my PC have same issue after Windows 10 update to 10586. For example ものべの-happy end-: ものべの-happy end-.1D16C1CE3B27713.crash.dmp, but it can run with NTLEA

**Comment by xd79077921** [comment]
Ok, after I uninstall Mactype every game runs great...........
But it's strange because I use Mactype since Windows 7 and every game is working. And after I upgrade to Windows 10 they still working..........until some Windows update crash my all games

**Comment by xupefei** [comment]
that has been abandoned for years. don't use it.
