### ISSUE TITLE
罪ノ光ランデヴー doesn't works

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#187]
it send locale error with locale-emulator.

but,
it works well when changing windows locale..

**Comment by xupefei** [comment]
minori games need some special treatment, but that will not be preformed by LE. Use AlphaROMdiE or [patch](https://sukebei.nyaa.eu/?page=view&tid=1945370) instead.

**Comment by mireado** [comment]
Um.... Sorry to border you again.
If I do not misunderstand that.
Did xupefei sensei mean that minori game(not crack and installer) also using special treatment?

**Comment by xupefei** [comment]
罪ノ光ランデヴー is a product of [Minori](http://www.amazon.co.jp/gp/product/B017EA3XCA) :)

Minori is a stupid company that always make international players unhappy.

**Comment by mireado** [comment]
OK. I understand.
Thank you for kind answer >_<
