### ISSUE TITLE
呃... 貌似有一份无关紧要的文件丢失了

### ISSUE THREAD

**Issue by fujita-nozomi** [xupefei/Locale-Emulator#188]
V2.1.1.0:
添加意大利语翻译（感谢 @JamesMaloney）。
运行之前检查 MS Gothic （ＭＳ ゴシック）字体。
LEProc.exe 接受附加参数。用法：LEProc.exe your_app.exe "arg1" "arg2"。你也可以把参数添加到桌面快捷方式里面。
怒草 2djgame.txt。 ←我错过了什么吗？咋docs文件夹找不到这个？

**Comment by xupefei** [comment]
http://bbs4.2djgame.net/home/forum.php?mod=viewthread&tid=393330
