### ISSUE TITLE
カスタムメイド3D2无法使用Locale-Emulator打开

### ISSUE THREAD

**Issue by BCwithCloud** [xupefei/Locale-Emulator#196]
游戏中有一个重要的程序（CM3D2x64）无法使用Locale-Emulator选项，可能是我电脑的原因，但还是希望能有人帮忙解决

**Comment by KagamiChan** [comment]
不是你电脑的原因，是 LE 不支持 64 位程序

**Comment by KagamiChan** [comment]
解决方法有两个：
- 用 LE 打开 x86 版本的 cm3d2，由于补丁是区分 x86 与 x64 的，因此可能还得再打补丁
- 用 [NTLEAS](https://ntlea.codeplex.com/)

**Comment by BCwithCloud** [comment]
@KagamiChan 感谢帮助，问题解决了

**Comment by BCwithCloud** [comment]
什么时候能支持64位系统呢，我挺喜欢这款软件的，希望能越来越完善！！

**Comment by KagamiChan** [comment]
@BCwithCloud 作者已经停止开发了。之前也并没有 64 位程序支持的计划，一方面改动量会很大，另一方面现在仅有 64 位的 ~~galge~~ 程序还是比较少的

**Comment by BCwithCloud** [comment]
那我拿一份源码应该没关系吧，我学编程的，想研究一下这个的原理

**Comment by regomne** [comment]
所谓开源项目，就是指任何人都可以拿来阅读和研究的。当然不同的开源协议在使用上有不同的限制，但是只是研究的话都可以随意做。
