### ISSUE TITLE
关于“伪造系统UI语言”的问题

### ISSUE THREAD

**Issue by AmyRose1288** [xupefei/Locale-Emulator#202]
[160428][TinkerBell]淫妖蟲 獄 フルパック版 ～凌触地獄退魔録～使用LE启动时有问题

其中的零篇在直接启动时全都是乱码，选项都看不出来，但是使用“伪造系统UI语言”选项后则是报错

报错内容：“应用程序无法正常启动(0xc0000034)。请单击“确定”关闭应用程序”

LE版本：Locale.Emulator.2.2.1.0.pre3
系统版本：Windows 10 CoreCountrySpecfic 10.0.10586.0

![20160505225848](https://cloud.githubusercontent.com/assets/19208524/15047215/880f0cbe-1316-11e6-97e5-d79542d1b7a7.png)
![qq 20160505231357](https://cloud.githubusercontent.com/assets/19208524/15047337/1a24b720-1317-11e6-855c-74f0729274fb.png)

**Comment by xupefei** [comment]
CoreCountrySpecfic 版本不支持这个选项。你需要升级到标准版或专业版。
