### ISSUE TITLE
Can't install Locale.Emulator

### ISSUE THREAD

**Issue by RZloli** [xupefei/Locale-Emulator#208]
when i click Install / Upgrade 
it said access is denied and show me these

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at LEInstaller.Form1.KillExplorer()
   at LEInstaller.Form1.buttonInstall_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LEInstaller
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Locale.Emulator.2.1.1.0/LEInstaller.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

How can I fix it?

**Comment by KagamiChan** [comment]
Did you run the installer with admin privilege?
What's your OS version (displayed on winver)?

**Comment by RZloli** [comment]
with admin privilege
![image](https://cloud.githubusercontent.com/assets/19405916/15319238/6e5593e8-1c5c-11e6-9337-ec4015a5a9b6.png)

**Comment by KagamiChan** [comment]
Are you insider program member and have already upgraded? If so, try the pre-release version.
If you don't know, press win+R and enter `winver`, then read the Windows version and internal version, it should be something like this in the red box:
![image](https://cloud.githubusercontent.com/assets/3816900/15320129/74e93eb2-1c61-11e6-8788-1b1c2141ba16.png)

And please also check your antivirus software.

**Comment by RZloli** [comment]
![image](https://cloud.githubusercontent.com/assets/19405916/15321691/a9ff2f0e-1c6a-11e6-9098-13fe1c27e083.png)
and antivirus software has trusted the application
