### ISSUE TITLE
Fake System UI Language feature not working with [mana] ゆめいろアルエット！

### ISSUE THREAD

**Issue by fro0116** [xupefei/Locale-Emulator#220]
Hi!

I was trying to get this game working without having to switch display languages, but neither NTLEA nor LE seems to be working. Here's some additional info:

LE version: v2.2.1.0.pre3
Game: ゆめいろアルエット！
Company: mana
Website: http://mana.product.co.jp/yumearu/
OS: Windows 10 Enterprise 64-bit build 10586
Error: none by LE, here's the ingame error: ![ingame error](http://i.imgur.com/ao3Gn61.png)

Note the time zone spoofing part seems to work. Once I change the display language to Japanese, the game starts working immediately without having to switch time zones.

Let me know if you need any more info.

Thanks!

**Comment by mireado** [comment]
Use AlphaROMdiE When launch Siglus engine.

**Comment by fro0116** [comment]
AlphaROMdiE worked great! I didn't know it could do that. Thanks for the tip!
