### ISSUE TITLE
Find LE install dir

### ISSUE THREAD

**Issue by Svinto** [xupefei/Locale-Emulator#228]
What is the recommended way for a script to check if LE is installed and finding the path to LEProc.exe?

I've found that the path to LEContextMenuHandler.dll can be found in the registry (see below). Since LEProc.exe is in the same directory it is trivial for a script to figure out the path from it.

HKEY_CLASSES_ROOT\CLSID\\{C52B9871-E5E9-41FD-B84D-C5ACADBEC7AE}\InprocServer32\CodeBase
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\\{C52B9871-E5E9-41FD-B84D-C5ACADBEC7AE}\InprocServer32\CodeBase

But I'm not sure if the GUID in the registry key path will be consistent for each computer and/or version of LE.

**Comment by xupefei** [comment]
Yes, the GUID is fixed. It is always [C52B9871-E5E9-41FD-B84D-C5ACADBEC7AE](https://github.com/xupefei/Locale-Emulator/blob/master/LEContextMenuHandler/FileContextMenuExt.cs#L37).
