### ISSUE TITLE
windows 10 更新至 1607 后，LEProc 工作不正常

### ISSUE THREAD

**Issue by taroxd** [xupefei/Locale-Emulator#239]
LE 版本 55765cdc92f88605709969904eb2ba2f3903fdcd
使用 VS 2015 community 编译

安装到 Context Menu ，以及从 Context Menu 运行是没问题的，全程无需管理员权限
但是用 LEProc 在命令行中启动的话，就会弹出 UAC 请求管理员权限
因为这个要求不太正常，所以我点了取消，过来汇报问题了 ;w;

目录下生成的 log 文件：
```
D:\local\Locale-Emulator\Build\Release\LEProc.exe
inst hp: 00000000
hook ntdll
init ret
```

config 是默认的，应该没什么意义
```xml
<?xml version="1.0" encoding="utf-8"?>
<LEConfig>
  <Profiles>
    <Profile Name="SiglusEngine.exe.le.config" Guid="2d91c409-c648-4e34-a17e-709208fec51d" MainMenu="false">
      <Parameter></Parameter>
      <Location>ja-JP</Location>
      <Timezone>Tokyo Standard Time</Timezone>
      <RunAsAdmin>false</RunAsAdmin>
      <RedirectRegistry>true</RedirectRegistry>
      <IsAdvancedRedirection>false</IsAdvancedRedirection>
      <RunWithSuspend>false</RunWithSuspend>
    </Profile>
  </Profiles>
</LEConfig>
```

对于 2.2.1.0 版，则是以另一种方式出错…… 目录下没有生成 log 文件。

![sp160811_192238](https://cloud.githubusercontent.com/assets/6070540/17587172/1f1226f8-5ff9-11e6-8130-c6cbf6790da4.png)

没记错的话，在 Windows 10 1511 版本中应该没有这个问题。
作为一个主要以命令行方式启动 LE 的用户来说……真心希望修复这个问题喵

**Comment by xupefei** [comment]
2210 里直接拖放的运行方式改了。以前是以日语运行，现在是以单独的 profile 运行。如果 profile 不存在，会弹出 LEGUI 的。那个 UAC 是谁弹的？
下面那个问题，目录下是不是没有 LECommonLibrary.dll?如果是的话，得先安装/卸载一次才有。

**Comment by taroxd** [comment]
弹出 LEGUI 并保存后弹 UAC。没有勾选已管理员身份运行。

UAC 提示中，应用程序为 `LEproc.exe -run MyProgram.exe`
