### ISSUE TITLE
TinkerBell社游戏伪造系统UI语言失败

### ISSUE THREAD

**Issue by bgtslhy** [xupefei/Locale-Emulator#242]
版本是最新的Locale.Emulator.2.2.1.0

![image](https://cloud.githubusercontent.com/assets/21053401/17690394/e4dabf9c-63c0-11e6-97cf-b45f7dab4d33.png)
一勾伪造系统UI语言就打开不了，出现弹框
![image](https://cloud.githubusercontent.com/assets/21053401/17690427/2e4677a2-63c1-11e6-9c95-a30c4778cddf.png)

游戏是淫妖蟲 獄，管理员打开也不行
不勾能正常打开游戏，右键左键能除对话乱码，选项和名字还是乱码

win10　版本是
![image](https://cloud.githubusercontent.com/assets/21053401/17690417/1a2b254c-63c1-11e6-9dda-e3ffa336a64f.png)

ＶＣ＋＋运行库也安装过了，还是没用

**Comment by xupefei** [comment]
新的伪造系统显示语言 选项，对任何**非单语言版**系统有效。
