### ISSUE TITLE
Local-Emulator clashes when lpLogfont is null in LeEnumFontFamiliesExA Function of Gdi32Hook.cpp

### ISSUE THREAD

**Issue by Roc-H** [xupefei/Locale-Emulator#250]
Hi there,

The local emulator clashes when the function LeEnumFontFamiliesExA  is called in Gdi32Hook.cpp when lpLogfont has NULL point value and there is not an exception handler for this. You can use attached small application to reproduce this issue. I can force the function returns in Gdi32Hook.cpp when lpLogfont is null in Gdi32Hook.cpp then it won't clash.
...
int NTAPI LeEnumFontFamiliesExA(HDC hdc, LPLOGFONTA lpLogfont, FONTENUMPROCA lpProc, LPARAM lParam, DWORD dwFlags)
{
    LOGFONTW            lf;
    PLeGlobalData       GlobalData = LeGetGlobalData();
    GDI_ENUM_FONT_PARAM Param;

     if (lpLogfont == NULL)
		return FALSE;

    Param.Callback      = lpProc;
    Param.GlobalData    = GlobalData;
    Param.lParam        = lParam;
    Param.Charset       = lpLogfont->lfCharSet;

    ConvertAnsiLogfontToUnicode(&lf, lpLogfont);

    return LeEnumFontFamiliesExW(hdc, &lf, LeEnumFontCallbackAFromW, (LPARAM)&Param, dwFlags);
}
....

 But there won't be any Font selection in my application.  Please suggest ideas/solutions or fix this bug? Thank you, 

R
[C++EnuFontFamiliesEx.zip](https://github.com/xupefei/Locale-Emulator/files/441424/C.EnuFontFamiliesEx.zip)

**Comment by xupefei** [comment]
What's the scenario in which you want to pass `NULL` to `lpLogfont`?
In my opinion you should at least fill it with `0`s.

**Comment by Roc-H** [comment]
Hi Xupefei,

When you said it is at least filled with Os, does it mean it supposed to be 0x00000000 which is still NULL, that is what I found in the LocaEmulator source code debug.  I still can reproduce this issue with 0x00000000 instead of NULL.  Thank you, 


R

**Comment by xupefei** [comment]
No, I mean
```
LOGFONT lf;
memset(&lf, 0, sizeof(lf));
```

**Comment by Roc-H** [comment]
Sorry, as I don't have access to the source code of another application. I really don't know how it get to 0x00000000 (null) value. Thanks,


R

**Comment by xupefei** [comment]
You can now grab the latest code and compile by yourself. It should resolve your issue.
PS: Debug logging is on be default. You can turn it off at https://github.com/xupefei/Locale-Emulator-Core/blob/96aa29c7b62dcb68a28c113a14c76b74db65b5df/LocaleEmulator/LocaleEmulator.h#L353.
