### ISSUE TITLE
反复安装没有右键菜单

### ISSUE THREAD

**Issue by avalon7989** [xupefei/Locale-Emulator#255]
右键菜单不显示.一直使用内置管理员账户,UAC是关闭的,上面英文的那个说是uac的问题,也不知道是不是,以前都是好的,反复安装还出现什么dll无法访问的弹窗

**Comment by xupefei** [comment]
> 上面英文的那个说是uac的问题,也不知道是不是

试试不就知道了？如果是的话，不就节省了我们两方的时间吗？
