### ISSUE TITLE
2.2.1.0无法安装

### ISSUE THREAD

**Issue by tmnt2** [xupefei/Locale-Emulator#272]
打开LEInstaller.exe后点击install/upgrade后右键菜单中没有LE的栏目（旧版本已经事先卸载了）

我的操作系统是win10 1607 14393.447

**Comment by xupefei** [comment]
不要日常使用使用管理员账户。

**Comment by syjsxxjy** [comment]
同样的问题。。。。可是我管理员用习惯了。。。
