### ISSUE TITLE
我想修改LocaleEmulator.dll这个dll的名字 但是运行不成功

### ISSUE THREAD

**Issue by GANHONG1995** [xupefei/Locale-Emulator#278]
源代码里面也没有修改的地方望指点

**Comment by UlyssesWu** [comment]
表示很难想到修改DLL名字有什么正当的理由。。。

**Comment by GANHONG1995** [comment]
因为游戏报外挂啊,想试试改名字过不过的了,拜托别把什么事情都想复杂了.

**Comment by UlyssesWu** [comment]
好吧……我想的太复杂了，您想的太简单了

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator-Core/search?utf8=%E2%9C%93&q=localeemulator.dll
https://github.com/xupefei/Locale-Emulator/search?utf8=%E2%9C%93&q=localeemulator.dll
