### ISSUE TITLE
在Win10 Pro 全中文环境运行AngelBeats! 1st beat 不能通过区域验证

### ISSUE THREAD

**Issue by Rambin** [xupefei/Locale-Emulator#283]
该死的Key验证了时区字符串，通过LE模拟的+9是“东京标准时间”，而AB!要求的是“日本（大阪、札幌、東京）”，导致验证不通过
系统里已经安装了日语语言包，而且即使在中文语言下，+9时区也显示的是“日本（大阪、札幌、东京）”（全部简体字），并没有显示“东京标准时间”
![ab](https://cloud.githubusercontent.com/assets/9563884/21610117/40ed2ef6-d201-11e6-91c5-f556bdb3380e.png)

**Comment by KagamiChan** [comment]
这个得用 alpharomdie，见 #241

**Comment by Rambin** [comment]
听说一开始的破解版过不了第三天，AlphaROMdiE能过吗？
我买了正版来着，然而切语言太麻烦了

**Comment by KagamiChan** [comment]
@Rambin 这就不了解了，没玩 = = alpharomdie 只是用来回避这个检查的。看了下 kf 那边的说法好像是原来首先放出的是假的
P.S. 还真的是你……

**Comment by Rambin** [comment]
那就先这样了，到第三天过不去了的话再去切语言。。。
现在已经确定切用户语言再用LE就能过了。。。不需要重启。。。
