### ISSUE TITLE
Not working properly in windowns 10 insider preview 15007(en_us)

### ISSUE THREAD

**Issue by ReinForce-II** [xupefei/Locale-Emulator#288]
Any program start with Locale Emulator crash with message

---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "C:\Program Files (x86)\****************" 

Microsoft Windows NT 10.0.15007.0 x64

NTDLL.DLL: 10.0.15007.1000

KERNELBASE.DLL: 10.0.15007.1000

KERNEL32.DLL: 10.0.15007.1000

USER32.DLL: 10.0.15007.1000

GDI32.DLL: 10.0.15007.1000

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
OK   
---------------------------

**Comment by mireado** [comment]
Wait for next update.
Basically, LE doesn't give guarantee for insider preview.
