### ISSUE TITLE
windows 10 preview 15007不能用

### ISSUE THREAD

**Issue by vatprcyq** [xupefei/Locale-Emulator#289]
系统语言中文简体
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "E:\.atc2.17in1\atc2\pds33.exe" 

Microsoft Windows NT 10.0.15007.0 x64

NTDLL.DLL: 10.0.15007.1000

KERNELBASE.DLL: 10.0.15007.1000

KERNEL32.DLL: 10.0.15007.1000

USER32.DLL: 10.0.15007.1000

GDI32.DLL: 10.0.15007.1000

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

**Comment by summivox** [comment]
同


---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "C:\~\app\xtw100\XTW100.exe" zh-CN



Microsoft Windows NT 10.0.15007.0 x64

NTDLL.DLL: 10.0.15007.1000

KERNELBASE.DLL: 10.0.15007.1000

KERNEL32.DLL: 10.0.15007.1000

USER32.DLL: 10.0.15007.1000

GDI32.DLL: 10.0.15007.1000



If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.
