### ISSUE TITLE
希望开发者能修复LE在win10 15014的兼容问题

### ISSUE THREAD

**Issue by sakuramisaki** [xupefei/Locale-Emulator#292]
之前在15007的时候就不能兼容了，我以为开发者太忙，就静静地等待更新。
哎，结果到了15014还是没有更新。

---------------------------
版本：Locale Emulator Version 2.2.1.0
---------------------------
错误代码: C0000142

系统：Microsoft Windows NT 10.0.15014.0 x64
错误弹窗显示内容：
NTDLL.DLL: 10.0.15014.1000

KERNELBASE.DLL: 10.0.15014.1000

KERNEL32.DLL: 10.0.15014.1000

USER32.DLL: 10.0.15014.1000

GDI32.DLL: 10.0.15014.1000

---------------------------
希望开发者能看到我的反馈。(●ˇ∀ˇ●)
---------------------------

**Comment by liehun10086** [comment]
同Win10 15014
更新Win10的Insider Preview之前运行没问题

---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "E:\CM3D2\1.42\CM3D2\CM3D2x86.exe" 



Microsoft Windows NT 10.0.15014.0 x64

NTDLL.DLL: 10.0.15014.1000

KERNELBASE.DLL: 10.0.15014.1000

KERNEL32.DLL: 10.0.15014.1000

USER32.DLL: 10.0.15014.1000

GDI32.DLL: 10.0.15014.1000
