### ISSUE TITLE
2.3.0.2 Installer 提示显示不完整

### ISSUE THREAD

**Issue by taroxd** [xupefei/Locale-Emulator#293]
![image](https://cloud.githubusercontent.com/assets/6070540/22391439/2a1708ee-e52c-11e6-9cb6-5d81eca351ee.png)

系统：Windows 10 Build 14393
DPI 缩放：125%

也许这个对话框需要拉得更大一些。

最后，祝开发者新年快乐！

**Comment by xupefei** [comment]
囧，我没强制字体。
