### ISSUE TITLE
LEGUI crash with no error

### ISSUE THREAD

**Issue by dogancelik** [xupefei/Locale-Emulator#296]
*LEGUI.exe* always crashes without errors if these 2 files don't exist in program directory:

* `LECommonLibrary.dll`
* `LEContextMenuHandler.dll` (not required really)

These 2 files don't exist in ZIP release.
You can only get them if you run *LEInstaller.exe* to create these 2 files.
Then you can start *LEGUI.exe* without errors.

You should be able to run GUI without installing anything to context menu.
You can run GUI but only after you run *LEInstaller.exe* once.

**Comment by xupefei** [comment]
This is intended.

All the LE components except `LEInstaller.exe` depend on the `LECommonLibrary.dll`. As the context menu `LEContextMenuHandler.dll` will be locked by explorer.exe after installation, it is not possible to replace this file later (when you are upgrading LE) if it is shipped by default in the ZIP file.

Finally I decide to not ship these DLLs, but extract them on-the-fly. This may cause some problems (like yours) however it makes the upgradation smoother.

**Comment by dogancelik** [comment]
I think we can find a better way for upgrading without having to pack these 2 DLLs inside the EXE file.
Because I use XYplorer, I can start LEGUI from XYplorer without having to install Context Menu Shell to Windows Explorer. It's less items in my context menu.

**Comment by xupefei** [comment]
I am afraid the current solution is the best when considering a few "dumb" users will cry when upgrading since those two files are locked by system.

I believe running LEInstaller once (without UAC prompt) is quite straightforward. Does this cause you any disturbance?

**Comment by dogancelik** [comment]
I agree running LEInstaller once is pretty straightforward, so no disturbance 😃
Just thought LEGUI could show a message something like "You need to run LEInstaller first" (better than crashing)

**Comment by xupefei** [comment]
> Just thought LEGUI could show a message something like "You need to run LEInstaller first" (better than crashing)

Unfortunately this is not possible 🙁 The crash happens even before the execution of any user code.

**Comment by xupefei** [comment]
I have somehow managed to show a messagebox instead of crash silently. How I am not able to do the same to all LE components as C# Winform application (e.g. LEProc.exe) will not run any user code before main() method.
