### ISSUE TITLE
允许global profile的alias

### ISSUE THREAD

**Issue by 0rt** [xupefei/Locale-Emulator#297]
我在文件工具里增加了一个按钮，选中文件时，点这个按钮会调用
d:\小工具\Locale Emulator.1.0.7.1\LEGUI.exe -run "选中的文件路径"
这样启动locale emulator的。自从不知那个版本以后，直接用路径做参数要求自定义profile，这样光盘等不可读介质就用不上这个按钮，刚刚看说明，是-runas guid 这样可以，但那个guid不好记，能不能增加可读的代号，
-runas japanNoAmdin "文件路径" 这样呢？

**Comment by xupefei** [comment]
编译最新的版本。
e916cf566c1f1d594f6aaeb8ed420a516b5851e3 里会使用全局 profile 里的第一个运行。语法是 `LEProc.exe "选中的文件路径"`。
