### ISSUE TITLE
Missing Core dll 

### ISSUE THREAD

**Issue by ibraha01** [xupefei/Locale-Emulator#300]
The threads written before don't answer the problem. 
i installed the locale emulator as administrator ,  windows updates  are up to date ,  the menu appears when i right click , the dlls LoaderDll.dll and LocaleEmulator.dll are present in the program directory , the directory is whitelisted in the antivirus ,any option clicked in the menu on any. exe file brings up the missing dll message box ,
i am using windows 10 , note: once the locale emulator was installed and was working fine months ago ,but not when i tried it today , in the header the error message brings up the wrong version number, maybe it it still in the registry somewhere?
![capture](https://cloud.githubusercontent.com/assets/11849651/22864775/0fb3347e-f160-11e6-9f18-9bdc10516908.PNG)

**Comment by xupefei** [comment]
You have an old version installed elsewhere.
Try find (e.g. Right click in the Task Manager, "open file location") and uninstall it, then reboot and install the new version once more.

**Comment by Teditt** [comment]
Look I know I'm not the guy who posted this and I don't mean to be rude, but no I do not. I installed it for the first time, hit build and this happens. And even if I did, what would that be labeled as in task manager?

**Comment by ibraha01** [comment]
Teditt is 100% correct ,nothing would be there in task manager   . 
The issue was resolved after i looked for all traces of the previous version from the registry removed them saved, and then restarted .
it now works fine .
If you are not confident enough to mess with the registry simply uninstall BOTH the old and the new Versions and restart . Then try to install the newer version , hopefully it would work .

**Comment by Teditt** [comment]
I have no idea what I'm looking for in either of those options.
