### ISSUE TITLE
Universal Windows Apps (UWA) / games support?

### ISSUE THREAD

**Issue by AndreasA** [xupefei/Locale-Emulator#302]
Windows universal apps by default use the current primary language. However, it would be nice to choose the language per app.
Locale emulator would be able to do so but those apps are not available as .exe, one only has a link in the startmenu to those apps or shortcuts which as destination have a string with a prefix like "Microsoft."
It would be nice if those apps / games would be supported too.

**Comment by xupefei** [comment]
The modern apps are running in a app container. I am afraid it is impossible for LE to support it.
BTW, all those apps are already unicode-compatible.
