### ISSUE TITLE
[suggest]Add context menu on 'program and features'

### ISSUE THREAD

**Issue by mireado** [xupefei/Locale-Emulator#303]
When uninstall program with Locale-emulator,
It need to find location where uninstaller is located.

It is really inconvenient.

So,
I want add context menu on "Control Panel\Programs\Programs and Features"

**Comment by xupefei** [comment]
You may uninstall the old version with the installer which from the new one. Make sure you have clicked both "Uninstall" button (if it is clickable).

**Comment by mireado** [comment]
um.. I was mean the feature that on control panel.
like this picture.

I can't see any context menu with "Programs and Features"
![298](https://cloud.githubusercontent.com/assets/4026514/24810674/1c231698-1bfe-11e7-9eaf-d797bd7a1007.png)
