### ISSUE TITLE
Clip Studio Paint Pro 台版无法绕过锁区

### ISSUE THREAD

**Issue by AT-Aoi** [xupefei/Locale-Emulator#306]
右键点击它的图标，没有 `Locale Emulator` 的选项。我用 `LEProc` 手动启动它，但是还是绕不过锁区。
我 `LE` 的设置为：

```
<Profile Name="Run in Taiwanese" Guid="397d1849-c68d-4a2c-80ee-d2a28b414c36" MainMenu="false">
  <Parameter></Parameter>
  <Location>zh-TW</Location>
  <Timezone>Taipei Standard Time</Timezone>
  <RunAsAdmin>false</RunAsAdmin>
  <RedirectRegistry>true</RedirectRegistry>
  <IsAdvancedRedirection>true</IsAdvancedRedirection>
  <RunWithSuspend>false</RunWithSuspend>
</Profile>
```

命令：

```
LEProc.exe -runas 397d1849-c68d-4a2c-80ee-d2a28b414c36 "D:\Apps\CELSYS\CLIP STUDIO 1.5 TC\CLIP STUDIO PAINT\CLIPStudioPaint.exe"
```

操作步骤：
1. 进入后输入许可证，按注册许可证。
2. 下一个页面中自动验证，下一步。
3. 验证成功进入到了软件主界面，弹出 `非工作对象的 OS` 的错误。
4. 点击后软件退出。

错误信息：

![os](https://cloud.githubusercontent.com/assets/3676278/23861765/0818eeaa-0846-11e7-8cde-3be11200f299.png)

- 系统：Windows 10 x64 专业版，版本 1607，OS 版本 14393.693
- 软件：Clip Studio Paint Pro 1.6.2.0 台版

**Comment by xupefei** [comment]
如果右键菜单里没有 LE 选项，那就说明它不被支持。就算用命令手动运行了这个程序，LE 还是不会被加载。
这程序可能是 64 位的。
