### ISSUE TITLE
Windows 10升级build 15063.11后LE无法运行

### ISSUE THREAD

**Issue by yzhan257** [xupefei/Locale-Emulator#312]
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: 0

Commands: SYSTEM_REPORT

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.0

KERNELBASE.DLL: 10.0.15063.0

KERNEL32.DLL: 10.0.15063.0

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.0

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

**Comment by xupefei** [comment]
Try the pre-release version: https://github.com/xupefei/Locale-Emulator/releases
