### ISSUE TITLE
Can't write greek in non unicode app

### ISSUE THREAD

**Issue by Malagad** [xupefei/Locale-Emulator#324]
After the latest windows update (creators version) I lost the greek fonts
in an old but extremely necessary app I use. I 've used the locale emulator and managed
to view everything as it should be but when I try to input greek text in the app
I see gibberish text.
Can anyone please help?

**Comment by xupefei** [comment]
Unfortunately it is not possible. The only solution is type the Greek characters somewhere else (e.g. in Notepad) and copy it to the application.
