### ISSUE TITLE
Locale Emulator无法保存参数

### ISSUE THREAD

**Issue by 123ysys** [xupefei/Locale-Emulator#331]
leguin已经install了，打开leguin.exe后无论怎么点保存都没有反应，右键点游戏也只有Locale Emulator的选项而没有Run in Japanese的选项，怎么办？

**Comment by taroxd** [comment]
leguin.exe 是什么？Locale-Emulator 并没有这个文件。

安装是用 LEInstaller.exe 安装的。

**Comment by 123ysys** [comment]
不好意思。记不太清楚文件名。LEInstaller.exe 打开后我install了，可是似乎没有作用。就像这样。

**Comment by 123ysys** [comment]
抱歉无法加图片。

**Comment by 123ysys** [comment]
@taroxd

**Comment by 123ysys** [comment]
@taroxd
