### ISSUE TITLE
Locale.Emulator.2.3.1.0无法运行

### ISSUE THREAD

**Issue by 123ysys** [xupefei/Locale-Emulator#332]
步骤是1.LEInstaller.exe
2.install for current user
3.显示成功
4.LEGUI.EXE
5.保存
无反应
这是怎么回事？不知道怎么传图，如果需要的话请教教我，谢谢。

**Comment by 123ysys** [comment]
@xupefei @taroxd

**Comment by 123ysys** [comment]
![Uploading IMG_20170424_220941.jpg…]()

**Comment by 123ysys** [comment]
![img_20170424_220927](https://cloud.githubusercontent.com/assets/27964272/25369550/4d16fadc-29b7-11e7-82ab-b78d7a6d9983.jpg)

**Comment by 123ysys** [comment]
![img_20170424_220941](https://cloud.githubusercontent.com/assets/27964272/25369603/c03d688e-29b7-11e7-86b9-c9a01a9423ba.jpg)

**Comment by UlyssesWu** [comment]
![请问你会截图吗](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1493107348715&di=8ce3132269f0bf06d538bf6f98972a72&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fw%3D580%2Fsign%3D4454cc8756da81cb4ee683c56266d0a4%2F698d6334970a304ecc258489d6c8a786c8175cd4.jpg)

不得不说这几张图是挺有水平的，关键的几个地方（LE路径下是否有`LEConfig.xml`；运行的是否是x64程序；是否是从压缩软件中直接运行）一个都不让人看到。

**Comment by 123ysys** [comment]
好的，新来的确实不懂这些规矩。路径下存在LEconfig.xml; x64架构，是解压后再运行的。 @UlyssesWu

**Comment by UlyssesWu** [comment]
LE不支持64位的程序，如果你一直试的游戏是64位的那就gg了。
请找一个32位的目标程序右键看看LE的菜单有没有Run In Japanese。
（注意不是让你对着LE的exe右键，是对着32位游戏的可执行程序右键）

**Comment by xupefei** [comment]
先解压再安装，不要直接双级压缩包里的LEInstaller。

**Comment by 123ysys** [comment]
不行啊。

**Comment by 123ysys** [comment]
其实问题应该出在保存那个步骤，上一版本的2.2.1.0是可以打开LEGUI这个文件并保存的，结果这个版本的保存不了。

**Comment by 123ysys** [comment]
其实问题应该出在保存那个步骤，上一版本的2.2.1.0是可以打开LEGUI这个文件并保存的，结果这个版本的保存不了。
