### ISSUE TITLE
Doesn't work w/ new version

### ISSUE THREAD

**Issue by itpcc** [xupefei/Locale-Emulator#348]
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "G:\Games\Active Chikan Vol11 Serious JK\oshigoto.exe" 

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.0

KERNELBASE.DLL: 10.0.15063.296

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.0

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
OK   
---------------------------

**Comment by taroxd** [comment]
Please update LE.

**Comment by itpcc** [comment]
Thanks, finally work properly! 👍
