### ISSUE TITLE
error when build source code 

### ISSUE THREAD

**Issue by abdelmoneimegypt** [xupefei/Locale-Emulator#356]
Hello
I'm download the source code file and open it using MS visual studio 2013
I get error : error CS1056: Unexpected character '$' this on all strings in the solution.
Please help me 
![le](https://cloud.githubusercontent.com/assets/29120734/26678041/dcceb9d8-46ce-11e7-8248-ec07c2f5b468.PNG)

**Comment by UlyssesWu** [comment]
You need VS2015 or higher to build this. It's C#6 syntax.
