### ISSUE TITLE
Error at run.. How to fix it?

### ISSUE THREAD

**Issue by JunKujikawa** [xupefei/Locale-Emulator#357]
![how to fix it](https://cloud.githubusercontent.com/assets/29139910/26717958/77c9a80a-47a9-11e7-83fe-eccb730bd26c.png)

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator#submit-issue:
> Due to the limited effort, we only accept issues under Windows 10 OS. If you are using another version of Windows, you may fix it by yourself.
