### ISSUE TITLE
無法開啟安裝整合包

### ISSUE THREAD

**Issue by qazqweqsq** [xupefei/Locale-Emulator#358]
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "D:\下載資料夾\哗哗MOD组整合版（重置版）\3DM游戏运行库合集v2.9\3DM运行库安装工具v2.9.exe" 

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.0

KERNELBASE.DLL: 10.0.15063.296

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.0

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator/releases/tag/v2.3.1.0
