### ISSUE TITLE
打不開...

### ISSUE THREAD

**Issue by emilylovenovels** [xupefei/Locale-Emulator#359]
跑出這個信息...但是我防毒軟體也關了啊...要怎麼辦qvq

---------------------------
Locale Emulator Version 2.3.1.0
---------------------------
Error Number: 80000003

Commands: "C:\Users\EMILY\Desktop\JIYUAN\jiyuan.exe" 

Microsoft Windows NT 6.1.7601 Service Pack 1 x64

NTDLL.DLL: 6.1.7601.23677

KERNELBASE.DLL: 6.1.7601.23677

KERNEL32.DLL: 6.1.7601.23677

USER32.DLL: 6.1.7601.23594

GDI32.DLL: 6.1.7601.23688

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
確定   
---------------------------

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator#submit-issue:
> Due to the limited effort, we only accept issues under Windows 10 OS. If you are using another version of Windows, you may fix it by yourself.
