### ISSUE TITLE
LE doesn't working. Error: C0000142

### ISSUE THREAD

**Issue by ZENOMx** [xupefei/Locale-Emulator#364]
ERROR: C0000142

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.0

KERNELBASE.DLL: 10.0.15063.296

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.0

I tried 2.3.1.0 and other versions but it's not working. Anybody help me please? 

Edit: Nevermind. I solved problem.

**Comment by ccwav** [comment]
How? would you share the case?
