### ISSUE TITLE
Issues with downloading DLsite product

### ISSUE THREAD

**Issue by J300MER** [xupefei/Locale-Emulator#369]
I've noticed since switching to Japanese Locale on Win10, it's helped, but there are still some games that can't be run. 
This usually occurs on games that use RPG Maker as the base of the project.
For example, Monster Girl Quest Paradox.
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "C:\Users\username\Documents\MSN\paradox\RJ150726.part1.exe" 

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.0

KERNELBASE.DLL: 10.0.15063.296

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.0

I'm running Windows Defender and don't seem to have any problems with most games, but certain RPG Maker games won't run well.
I've tried Firefox and Chrome, but neither seem to change the outcome.

Any solutions would be greatly appreciated ^_^

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator/releases/tag/v2.3.1.0

**Comment by taroxd** [comment]
Besides running the game with locale emulator, you should also extract the games with Shift-JIS codepage if it was in zip format.
