### ISSUE TITLE
ListBox 内的内容缩到一起了

### ISSUE THREAD

**Issue by shengkee** [xupefei/Locale-Emulator#374]
如下图所示，第一张是program用Applacale在window XP里正常显示的Listbox，第二张是program没有用任何Locale软件在windows10中的显示，第三张显示的是用Loacal Emulator在window 10里显示的，里面的数据内容都缩到了左边，包括“周标准用量”“现有存量”“建议定量”“实际定量”的箱数和零数的显示也不在位子上，不能正常显示：

![image](https://user-images.githubusercontent.com/29667746/27504407-9798c766-583d-11e7-80c4-7dfc970c9e65.png)

![image](https://user-images.githubusercontent.com/29667746/27504475-0d6850aa-583f-11e7-9bff-610bf8adfe11.png)

![image](https://user-images.githubusercontent.com/29667746/27504417-b2902e6a-583d-11e7-8373-1ab6e139ab3c.png)

**Comment by xupefei** [comment]
字体问题。这个 listbox 用的是 TAB 对齐，XP 那图里是 Courier 点阵字体。你试试从 XP 机器上把 Courier 字体复制过来。注意是 Courier 不是 Courier New。

**Comment by shengkee** [comment]
第二幅图显示的是同样的环境下没有用Loacal Emulator的显示结果，第三幅图是用了Loacal Emulator之后的显示结果。

**Comment by xupefei** [comment]
你可以用资源修改器把那个框的字体改成一个等宽的。

**Comment by shengkee** [comment]
还是不行，我可能没把问题解释清楚，在没有用Loacal Emulator的时候program显示是正常的，用了Loacal Emulator之后才出现这个情况的， program用的是space(n)显示空格字符来做对齐，看起来Loacal Emulator忽略掉空格字符串。
