### ISSUE TITLE
where are the files located?

### ISSUE THREAD

**Issue by SummGai** [xupefei/Locale-Emulator#380]
avast has blocked LE from running and I can't add it as trusted because I don't know where the files are.

**Comment by xupefei** [comment]
I don't know either. You should remember where you put them.

**Comment by xupefei** [comment]
BTW, I just brought a code certificate. Avast should now make fake report from the next version of LE.

**Comment by SummGai** [comment]
I installed the files. The nature of Avast is such that I need an EXE or file folder to exclude. I have neither, as such App Locale bluntly won't work on my system.

if you developed this software you should know where your installer puts the files, as it is all that happens when I run the installer is that it installs the files without any indication of where they go.

**Comment by taroxd** [comment]
The installer only adds shell integration. The files are in wherever you extract the zip.
