### ISSUE TITLE
Locale Emulator does not do anything with the right-click context menu.

### ISSUE THREAD

**Issue by bckps7336** [xupefei/Locale-Emulator#386]
Hello,
I recently want to use some software on my new laptop. I followed the usual way to install LE, but when I attempt to run the application, nothing has appeared. 

- LEProc.exe works
- I tried another software with no unicode characters in the path, doesn't work either 
- I also tried run a normal .exe file, but also nothing happens.

List of tested exe files:

1. D:/蒼の彼方のフォーリズム/AoKana.exe
2. D:/1.7.8/KanAuto.exe
3. D:/UserBenchMark.exe

Tested LE versions:

- 2.3.1.1
- 2.3.1.0

Tested Windows versions:

- Windows 10
- Windows 7

Sorry but I could not provide any dump files and screenshots as the program does not provide any of these.
Please let me know if I could use something to get some debug info.

**Comment by bckps7336** [comment]
Yes. Yesterday I also tried an older version(2.2.1.0), which did show something but an error code C00000142. I believe it is due to incompactibility. FYI it(LEProc.exe) also asks for admin rights.

**Comment by xupefei** [comment]
The installation in 2210 works exactly the same as "install for current user" in later versions. Therefore your issue is caused by something else.
I suggest you do the following:
0) download the latest version, turn off your antivirus software
1) run LEInstaller as admin
2) click both "Uninstall for xxx" button (if it is clickable)
3) reboot
4) run LEInstaller again, without admin right
5) install again
3) reboot again (may not necessary)

**Comment by bckps7336** [comment]
I moved to another computer which runs Win10, and I found that the folder lacks of LEProc.exe.
I re-downloaded the 2.3.1.1 version and do a fresh install (Like in your instructions), and it works again. I will test it again with my main computer later and see if that is the gist of the problem.

**Comment by bckps7336** [comment]
After messing around, I have confirmed that the file integrity was the main problem.
For other people who face the same problem, please validate that your LE folder consists of all files you downloaded from the compressed file, as some antivirus software may unreportedly remove some file in the directory.
Thanks xupefei for your software and helpful support, it really benefits many people includes me.
