### ISSUE TITLE
求解，转区后文字输入乱码

### ISSUE THREAD

**Issue by HayateL** [xupefei/Locale-Emulator#389]
输入日文或中文都是乱码的，英文没问题。
之前是没有问题的，后来重装了一次系统就这样了。试过重装系统、安装各种运行库，都没用。。
> 

---------------------------
Locale Emulator Version 2.3.1.1
---------------------------
Error Number: 0

Commands: SYSTEM_REPORT

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.447

KERNELBASE.DLL: 10.0.15063.483

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.483

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

**Comment by xupefei** [comment]
请先搜索：https://github.com/xupefei/Locale-Emulator/issues?utf8=%E2%9C%93&q=IME
此问题无法解决，只能先在其他地方输入再复制进来。
