### ISSUE TITLE
My PC doesn't support the Emulator

### ISSUE THREAD

**Issue by aruto77** [xupefei/Locale-Emulator#393]
i have turned off all antivirus but still can't support and the message always shown
---------------------------
Locale Emulator Version 2.0.1.0
---------------------------
Error Number: C0000142

Commands: "E:\Apps\YUZUSOFT\天色＊アイルノーツ\AmairoIsleNauts.exe" 

Microsoft Windows NT 6.2.9200.0 x64

NTDLL.DLL: 6.2.15063.447

KERNELBASE.DLL: 6.2.15063.483

KERNEL32.DLL: 6.2.15063.296

USER32.DLL: 6.2.15063.0

GDI32.DLL: 6.2.15063.483

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
OK   
---------------------------

**Comment by taroxd** [comment]
https://github.com/xupefei/Locale-Emulator/releases
