### ISSUE TITLE
win10 更新后无法使用

### ISSUE THREAD

**Issue by YingjieChen1994** [xupefei/Locale-Emulator#405]
某天手抖更新win10后locale-Emulator无法使用
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "D:\Alicesoft\超昂神騎エクシール\Ixseal.exe" 

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.447

KERNELBASE.DLL: 10.0.15063.502

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.483

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

除此之外，adsafe也无法使用
希望能够帮助我解决这个问题，谢谢

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator/releases
