### ISSUE TITLE
cannot use Locale Emulator after Window 10 updated 

### ISSUE THREAD

**Issue by victorlwf** [xupefei/Locale-Emulator#411]
---------------------------
Locale Emulator Version 2.2.1.0
---------------------------
Error Number: C0000142

Commands: "C:\wh6通用版\mytrader_whsp.exe" 

Microsoft Windows NT 10.0.15063.0 x64

NTDLL.DLL: 10.0.15063.447

KERNELBASE.DLL: 10.0.15063.502

KERNEL32.DLL: 10.0.15063.296

USER32.DLL: 10.0.15063.0

GDI32.DLL: 10.0.15063.483

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------

請協助解決, 謝謝

**Comment by taroxd** [comment]
https://github.com/xupefei/Locale-Emulator/releases
