### ISSUE TITLE
Win10 1703 x64 无法运行

### ISSUE THREAD

**Issue by EnchanterC** [xupefei/Locale-Emulator#416]
Win10 1703版本 64位操作系统，无法运行Locale Emulator 2.3.1.1，LEInstaller可打开，但LEGUI打开后点击保存没反应。
这可是我的笔记本的必备软件之一，但现在无法使用了TAT
虽然我知道此软件在64位系统上无法运行，但厉害的制作者也许能研发出可以在64位系统上运行的版本吧。
感谢制作者研发出了这么厉害这么便利的软件！

**Comment by bestpika** [comment]
我就是用這個版本可以運作耶

**Comment by EnchanterC** [comment]
我还以为是因为我的系统是64位的所以无法运行，既然这样的话那是怎么回事呢……

**Comment by taroxd** [comment]
你有没有把 LE 放到 Program Files 这样的地方？如果有的话请给予写入文件夹的权限或者移到别的地方。

**Comment by EnchanterC** [comment]
没有，我尝试过把LE放在Downloads、Program Files、Program Files (×86)文件夹下，尝试过用管理员身份运行，结果都是点击LEInstaller显示Install finished，但点击LEGUI后却无法保存，点击LEGUI界面的“保存”没反应。在exe文件上的右键菜单也无任何变化。

**Comment by bestpika** [comment]
會不會是防毒軟體造成？

**Comment by EnchanterC** [comment]
我把其余软件包括防毒软件件关掉也还是那样……重启过什么的也都试过，绝望了……

**Comment by qwerty258** [comment]
有个软件叫`ShellExView`，用它来看看资源管理器都注册了哪些扩展插件，如果存在`LEContextMenuHandler.FileContextMenuExt`，就说明安装成功了；不存在则说明没安装成功。

**Comment by Richardlx** [comment]
我的也是1703之后不能使用了 更新了2.3.1.1之后仍然C0000142 ;w;

**Comment by herolulu** [comment]
正版WIN10更新到最新版本，完全没有任何问题。。。 =。=

**Comment by zasdza** [comment]
cmd运行winver看下具体版本？
我这里1703可以
15063.540

**Comment by Richardlx** [comment]
nvm...睡了一觉起来更新了KB4038788之后就没问题了

**Comment by EnchanterC** [comment]
安装了vcredist组件后问题已解决，可正常运行，感谢制作者和答疑者！
