### ISSUE TITLE
C0000142多次错误无解

### ISSUE THREAD

**Issue by wsl98501** [xupefei/Locale-Emulator#429]
Locale Emulator Version 2.0.1.0
---------------------------
Error Number: C0000142

Commands: "C:\lingeries\lingeries.exe" 

Microsoft Windows NT 6.2.9200.0 x64

NTDLL.DLL: 6.2.15063.608

KERNELBASE.DLL: 6.2.15063.608

KERNEL32.DLL: 6.2.15063.296

USER32.DLL: 6.2.15063.608

GDI32.DLL: 6.2.15063.483

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

已经下载过LOE多个版本，各种姿势解锁无门。

**Comment by taroxd** [comment]
https://github.com/xupefei/Locale-Emulator/releases/latest
那请下载最新版本

**Comment by wsl98501** [comment]
谢谢已解决！
