### ISSUE TITLE
LE运行总是出问题，

### ISSUE THREAD

**Issue by tkdjjs** [xupefei/Locale-Emulator#442]
当直接运行LEProC的时候，会出现error0
当右键运行相关游戏的时候会出现后图
曾经好用过，但是一段时间之后就变成现在这样了。
![0ys xq1s79q6i htma6j74](https://user-images.githubusercontent.com/33284624/32274771-73fb22e6-bf43-11e7-98e0-c50cbd2c64e5.png)
![wgyk gvy1 mpvjr tvulk o](https://user-images.githubusercontent.com/33284624/32274775-75f407de-bf43-11e7-8f3f-314c4ee9db43.png)

**Comment by xupefei** [comment]
https://github.com/xupefei/Locale-Emulator/releases
