### ISSUE TITLE
The language of timezone cannot get emulated with location

### ISSUE THREAD

**Issue by HasukaPoi** [xupefei/Locale-Emulator#445]
---------------------------
日本語版Windows判定
---------------------------
This Game is Japan Only

このゲームは日本国内でのみプレイ可能です。

動作させるには 『 日本語版Windows 』 が必要です。

コンピュータの現在のタイムゾーン設定は 『 东京标准时间 』 です。

タイムゾーンを 『 日本（大阪、札幌、東京） 』 に設定して下さい。

ゲームを終了します。

↑
As this, the timezone has changed to UTC+9 but the **language of timezone** is still Chinese (the current layout language of OS) unless I manually change the layout language of Windows to Japanese the game doesn't work.
Hope to bug fix :)

**Comment by xupefei** [comment]
Please use AlphaROMdiE.

**Comment by HasukaPoi** [comment]
I’ll try, thanks for answering
