### ISSUE TITLE
When the application language is English, LE is not displayed in the context menu

### ISSUE THREAD

**Issue by eai04191** [xupefei/Locale-Emulator#451]
I am using the Japanese version of Windows 10 64 bit in the Japanese locale.
Some applications do not work well in Japanese locale, so I need to start with English locale.

I installed LE for my users.
And I confirmed that there is no LE in some exe's context menu.

Looking at the properties, those exes were in English (US) languages.

I would like to launch these applications in English locale.
What should I do?

---

![image](https://user-images.githubusercontent.com/3516343/33227447-53be70b8-d1e6-11e7-85b3-9938749270ff.png)

From left, English, Japanese, not specified

![image](https://user-images.githubusercontent.com/3516343/33227426-ff8acbe0-d1e5-11e7-9e82-4382fcd4ae6d.png)

There is no LE only for English applications.

**Comment by xupefei** [comment]
LE will not show context menu for 64-bit applications.
Your "ffxiv_sta***.exe" is 64-bit.

**Comment by eai04191** [comment]
OK. Thank you for replying.
