### ISSUE TITLE
在win10 rs4预览版中无法正常使用

### ISSUE THREAD

**Issue by PtNan** [xupefei/Locale-Emulator#466]
win10 rs4 版本为build 17063
出现无法使用的问题，没有转区效果，为了正常打开游戏（及其安装程序）需要更改系统语言以及非Unicode程序的语言。希望在rs4正式版发行后能及时更进

**Comment by xupefei** [comment]
See #462.

**Comment by RemainingWInd** [comment]
same problem

**Comment by xupefei** [comment]
Solved.
