### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by xXCygnus13Xx** [xupefei/Locale-Emulator#63]
LE fails at launch.

---------------------------
Locale Emulator Version 1.4.0.1
---------------------------
Launch failed.

Commands: "C:\Users\*****\Downloads\g\プレグナントブレイブver1_2\Game.exe" 

Error Number: C0000135

Administrator: True

If you have any antivirus software running, please turn it off and try again.

If you think this error is related to LE itself, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
OK   
---------------------------

Log Name:      Application
Source:        Application Error
Date:          1/8/2015 9:15:26 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Faulting application name: LEProc.exe, version: 0.0.0.0, time stamp: 0x54809763
Faulting module name: LoaderDll.dll, version: 0.0.0.0, time stamp: 0x53a7f2a3
Exception code: 0xc0000005
Fault offset: 0x000018bf
Faulting process id: 0x2b04
Faulting application start time: 0x01d02bb221ae81b1
Faulting application path: C:\Users\*****\Downloads\Locale.Emulator.1.4.0.1\Locale Emulator\LEProc.exe
Faulting module path: C:\Users\****\Downloads\Locale.Emulator.1.4.0.1\Locale Emulator\LoaderDll.dll
Report Id: 5f6afe20-97a5-11e4-826d-8019343b8665
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-01-09T02:15:26.000000000Z" />
    <EventRecordID>8065</EventRecordID>
    <Channel>Application</Channel>
    <Computer>********</Computer>
    <Security />
  </System>
  <EventData>
    <Data>LEProc.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>54809763</Data>
    <Data>LoaderDll.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>53a7f2a3</Data>
    <Data>c0000005</Data>
    <Data>000018bf</Data>
    <Data>2b04</Data>
    <Data>01d02bb221ae81b1</Data>
    <Data>C:\Users\*****\Downloads\Locale.Emulator.1.4.0.1\Locale Emulator\LEProc.exe</Data>
    <Data>C:\Users\******\Downloads\Locale.Emulator.1.4.0.1\Locale Emulator\LoaderDll.dll</Data>
    <Data>5f6afe20-97a5-11e4-826d-8019343b8665</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Second Item:
Log Name:      Application
Source:        .NET Runtime
Date:          1/8/2015 9:15:26 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ****
Description:
Application: LEProc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at LEProc.LoaderWrapper.LeCreateProcess(IntPtr, System.String, System.String, System.String, UInt64, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
   at LEProc.LoaderWrapper.Start()
   at LEProc.Program.DoRunWithLEProfile(System.String, LECommonLibrary.LEProfile)
   at LEProc.Program.RunWithIndependentProfile(System.String)
   at LEProc.Program.Main(System.String[])

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-01-09T02:15:26.000000000Z" />
    <EventRecordID>8064</EventRecordID>
    <Channel>Application</Channel>
    <Computer>*******</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: LEProc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at LEProc.LoaderWrapper.LeCreateProcess(IntPtr, System.String, System.String, System.String, UInt64, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
   at LEProc.LoaderWrapper.Start()
   at LEProc.Program.DoRunWithLEProfile(System.String, LECommonLibrary.LEProfile)
   at LEProc.Program.RunWithIndependentProfile(System.String)
   at LEProc.Program.Main(System.String[])
</Data>
  </EventData>
</Event>

**Comment by xXCygnus13Xx** [comment]
Windows 8.1

**Comment by xupefei** [comment]
32 or 64 bit?

**Comment by xXCygnus13Xx** [comment]
64

**Comment by xupefei** [comment]
Hello, I have tried this game on my Windows 8.1 x64 PC and it work with LE without any issue.
I think you should turn off your antivirus / security software, download & reinstall LE and try again.

I will now close this issue.
