### ISSUE TITLE
对 dll 的访问被拒绝

### ISSUE THREAD

**Issue by taroxd** [xupefei/Locale-Emulator#65]
环境：win7，x64

**Comment by xupefei** [comment]
请提供详细步骤或出错情况。
安装路径包含空格是没有问题的，因为你是第一个出现这问题的人……

**Comment by taroxd** [comment]
嗯，很抱歉，大概是我搞错了

我之前出错，然后把文件夹中的空格删掉之后就好了，我以为是空格导致的。

出错情况大致是 dll 加载失败什么的。现在没法再重现了……

**Comment by taroxd** [comment]
已经重现。报错截图及信息如下。（注：虽然地址是在 Release 文件夹里面，但是并不是我这里的 build，是直接下载的二进制文件）

![图1](http://image16.poco.cn/mypoco/myphoto/20150216/20/17366691320150216202252016.png?480x177_130)

![图2](http://image16-c.poco.cn/mypoco/myphoto/20150216/20/17366691320150216202310011.png?441x349_130)

报错信息：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.UnauthorizedAccessException: 对路径“E:\local\Locale-Emulator\Build\Release\LECommonLibrary.dll”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 LEInstaller.Form1.ReplaceDll()
   在 LEInstaller.Form1.buttonUninstall_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LEInstaller
    程序集版本:0.0.0.0
    Win32 版本:0.0.0.0
    基本代码:file:///E:/local/Locale-Emulator/Build/Release/LEInstaller.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.18408 built by: FX451RTMGREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by xupefei** [comment]
LECommonLibrary.DLL 的属性窗口里有这一项吗？ 

![](http://i.imgur.com/aedGzum.png)

如果没有的话，能够成功手动移动这个 DLL 进入回收站吗?

**Comment by xupefei** [comment]
请测试 1411 版本： https://github.com/xupefei/Locale-Emulator/releases。

**Comment by taroxd** [comment]
已经解决，谢谢！
