### ISSUE TITLE
Launch failed！

### ISSUE THREAD

**Issue by TCL9** [xupefei/Locale-Emulator#67]
---------------------------
Locale Emulator Version 1.4.1.0
---------------------------
Launch failed.

Commands: "D:\Game\月に寄りそう乙女の作法2\月に寄りそう乙女の作法２.exe" 

Error Number: C0000142

Administrator: True

If you have any antivirus software running, please turn it off and try again.

If you think this error is related to LE itself, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

试过许多版本都不行。所有杀软都已经卸载了...
另一台电脑可以，完全不明白为什么？
麻烦了

**Comment by xupefei** [comment]
If you decide to submit a ticket, please indicate the following information in the issue:

- **Version of your OS (Win7 / 8 / 8.1 etc.) and system type (32 / 64 / 65536bit).**
- Name and company of the broken application.
- Error message produced by Locale Emulator, including error number, application path, version of Locale Emulator and UAC information.
- Attach a screen capture if the application runs but not running correctly.

**Comment by TCL9** [comment]
Win 7 64 bit
月に寄りそう乙女の作法２, Navel

**Comment by TCL9** [comment]
而且在两台不同的win 7 64bit电脑上试，一台可以，一台不可以...
不可以的把所有杀软都卸载了，重新装，也是不行...
非常奇怪

**Comment by xupefei** [comment]
请试一下 Release 中的 1412.pre1 版本，如仍然报错，还请把报错信息贴上来。

**Comment by TCL9** [comment]
---------------------------
Locale Emulator Version 1.4.1.2
---------------------------
Error Number: C0000142

Commands: "D:\Game\乙女理論とその周辺\乙女理論とその周辺.exe" 



Microsoft Windows NT 6.1.7601 Service Pack 1 x64

NTDLL.DLL: 6.1.7600.16385 (win7_rtm.090713-1255)

KERNELBASE.DLL: 6.1.7601.17965 (win7sp1_gdr.121004-0333)

KERNEL32.DLL: 6.1.7601.17965 (win7sp1_gdr.121004-0333)

USER32.DLL: 6.1.7601.17514 (win7sp1_rtm.101119-1850)

GDI32.DLL: 6.1.7601.18577 (win7sp1_gdr.140822-1508)



If you have any antivirus software running, please turn it off and try again.

If you think this error is related to LE itself, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.





You can press CTRL+C to copy this message to your clipboard.


---------------------------
确定   
---------------------------

还是不行...就这台机器上不行，在其他两台win7 x64上都可以的。。。是系统自带的某个dll之类的错误了吗？

**Comment by xupefei** [comment]
根据 http://www.geoffchappell.com/studies/windows/win32/ntdll/history/index.htm 所说，在装过 SP1 的 win7 系统里，ntdll.dll 的版本号至少应该为 6.1.7601.17514，可是你这系统里，这个 DLL 确是没装过 SP1 的版本（ 6.1.**7600**.16385 (**win7_rtm**.090713-1255)）。
如果你也不知道怎么回事的话，重装吧……
