### ISSUE TITLE
Win10 9926 64bit，模拟区域失败

### ISSUE THREAD

**Issue by lialosiu** [xupefei/Locale-Emulator#68]
**Win10 9926 64bit** 版本， LE **v1.4.1.1**

右键->LE->日区运行，程序能跑起来，但是程序还是用本地区域码来运行……

嘛，虽然Win10这还是TP的版本没啥好说的……

不过我看changelog写着 **v1.4.1.0** 增加了对Win10支持，还是来报告下吧(:3」∠)

**Comment by xupefei** [comment]
See #49.
