### ISSUE TITLE
Locale Emulator doesn't work!

### ISSUE THREAD

**Issue by AsukaLangleyfag** [xupefei/Locale-Emulator#70]
OS: Windows 10 Enterprise Technical Preview x64
Software: Warcraft 3 1.26.0.6401
Version of Locale Emulator: 1.4.1.1
My locale: jp-JP
Emulated locale: ru-RU (Russian (Russia) in menu)
P.S. 1.4.1.0 worked fine on Windows 7 Enterprise SP1
![should be "тест"](http://i.imgur.com/bpOPA6l.jpg)
I wrote "тест", but got this instead.
![settings screeshot](http://i.imgur.com/lWjvmKu.png)

**Comment by xupefei** [comment]
Sorry, till now only Windows 10 build number below (and not equal to) 9926 is supported.
Full support of Windows 10 will come following the release of RTM version
