### ISSUE TITLE
为什么我安装完LE后右键打开后没有run as japenese的选项？

### ISSUE THREAD

**Issue by Alexyuyiyan** [xupefei/Locale-Emulator#71]

**Comment by xupefei** [comment]
运行一次 LEGUI.exe 就有了。

**Comment by Alexyuyiyan** [comment]
貌似还是不行，我是win8.1的系统，没有问题吧？

**Comment by xupefei** [comment]
win8没问题，把LE安装目录截图看看都有什么文件

**Comment by Alexyuyiyan** [comment]
![image](https://cloud.githubusercontent.com/assets/11468233/6649347/321c87b6-c9a5-11e4-9517-42b54696b300.png)

**Comment by xupefei** [comment]
你发现了吗，这是一个zip文件，不是一个文件夹

**Comment by Alexyuyiyan** [comment]
我只能找到zig的LE文件夹=-=，另外一个只有installer在里面

**Comment by xupefei** [comment]
你把这个zip里的文件全解压到一个文件夹里，然后安装啊

**Comment by Alexyuyiyan** [comment]
这个zig是已经解压了的。。是一个文件，

**Comment by Alexyuyiyan** [comment]
![image](https://cloud.githubusercontent.com/assets/11468233/6649408/7b99b674-c9a6-11e4-88f2-fd85ee304205.png)

**Comment by Alexyuyiyan** [comment]
我开打过LEGUI.exe，但是什么都没变过

**Comment by xupefei** [comment]
我囧
你倒是把LocaleEmulatorX.X.X.X.zip 里面的一堆文件解压出来啊

**Comment by Alexyuyiyan** [comment]
额。现在可以了，貌似没有拖出来就识别不了。恋がさくころ桜どき这个游戏貌似用这个打不开？

**Comment by Alexyuyiyan** [comment]
不过问题倒是解决了，有点弱智了=-=， 多谢多谢

**Comment by xupefei** [comment]
我也不知道，但之前没人反馈过这游戏有问题。

**Comment by Alexyuyiyan** [comment]
我是看贴吧建议用你这个LE才能打开，可是我打不开。。别的游戏貌似可以

**Comment by Alexyuyiyan** [comment]
![image](https://cloud.githubusercontent.com/assets/11468233/6649574/24ea794a-c9aa-11e4-82a8-e6d7150bc32e.png)

**Comment by Alexyuyiyan** [comment]
知道是怎么回事么=-=

**Comment by Alexyuyiyan** [comment]
重新复制一次就可以了，问题解决了。这个转区软件确实是我用过最好的，谢谢
