### ISSUE TITLE
Replace COM with a stable solution

### ISSUE THREAD

**Issue by HYBRID-BEING** [xupefei/Locale-Emulator#72]
Windows 8.1 Single Language (Russian), any software.
LEGUI.exe crashes and no shortcut appears on desktop. On a side note, if japanese characters are present in path instead, they will be substituted with "?" in shortcut.

**Comment by xupefei** [comment]
Could you give me an example of a path contains such characters?

**Comment by HYBRID-BEING** [comment]
Hmm, now that i think about that using "non-unicode" might not have been correct. It happens for me with japanese in folder and executable names. Edited OP.

**Comment by xupefei** [comment]
I tried creating shortcut with file named as `D:\いろは\にほへと.exe` but it seems the shortcut is created successfully, so I think it is not related to these Japanese characters.

I have created a debug LEGUI.exe which can popup a message when creating shortcut. Would you like to try out? If so please extract this file into LE directory and drag the exe onto LEGUI.debug.exe.

**Comment by HYBRID-BEING** [comment]
Looking at my event log (http://rghost.net/6Q8HtK8vN) - might be something wrong with my system, but yeah, i'll give it a try.

**Comment by xupefei** [comment]
Try put this file in LE directory, it should solve your problem:
https://anonfiles.com/file/43596f3d95b04d722aaee78520d52ff7

Actually I don't know the reason why this happens, but I searched on the Internet and see many people have met the same problem :(

**Comment by HYBRID-BEING** [comment]
It didn't help nor sfc /scannow did.

**Comment by xupefei** [comment]
After you put that file into LE dir, did you went to the Properties page and click "Unlock File"?

**Comment by HYBRID-BEING** [comment]
Sorry for the late response, but yes, the file wasn't locked actually. I'm not in possesion of my laptop with 8.1 atm, but i tried creating shortcut on two 7s (Pro 64bit and Home Premium 32bit) on this version of LE (come to think of it, i never mentioned that i've tried v1.4.1.1) with the same result. I even tried v1.2.0.1, but nope, still crashed for japanese name and still placed broken shortcut for exe with japanese path. Could you upload that .dll once more since anonfiles is down?

**Comment by xupefei** [comment]
Please download version 1060 from here: https://mega.co.nz/#F!QYlWRDYK!SZngRnKE1RMKlvCQJGcQBg

Try it and post the result here.

**Comment by HYBRID-BEING** [comment]
Nope, still crashes. I even tried using it on Win 7s Pro 64bit on Virtual Box (after installing .NET Framework 4.0 CP, of course), but to no avail.

**Comment by xupefei** [comment]
Thanks for the reply.
I think this is caused by the COM complement used to create shortcut files. I will change the COM to another solution. I hope this will be solved in the upcoming stable version.
For now, you can use https://leshortcut.codeplex.com/ instead.

**Comment by HYBRID-BEING** [comment]
Wow, i'd be actually fine with editing copied shortcuts for a time being, but thanks anyway. The utility works, btw.

**Comment by xupefei** [comment]
Would you please try the newest pre-release version and check if everything works now?

**Comment by HYBRID-BEING** [comment]
Yeah, with this version no crash occurs on shortcut creation.

**Comment by xupefei** [comment]
Thanks :)
