### ISSUE TITLE
cannot save file in "キャラクターなんとか機"

### ISSUE THREAD

**Issue by taroxd** [xupefei/Locale-Emulator#75]
Download: http://khmix.sakura.ne.jp/download.shtml

When I try to save the character to file, the dialog just won't show.
![picture](http://image16.poco.cn/mypoco/myphoto/20150322/21/17366691320150322210006081.png?646x508_130)

However, if I start the application without Locale Emulator, it works fine except for all the weird characters. :) 

I am looking forward to a solution.

---

总之，用了这货就打不开保存文件的对话框，不用这货就乱码。所以求修复~

**Comment by xupefei** [comment]
删除 LERegistry.xml 后双击 LEUpdater.exe 即可解决问题。
BTW，这个问题之前也有人说过，但我一直无法重现。
方便提供一下系统详细信息么？
* Win7/8/8.1？
* 32位还是64位？

如果是 32 位：

* X:\Windows\System32\kernel32.dll 版本号（右键属性->详细信息->文件版本）？
* X:\Windows\System32\KernelBase.dll 版本号？
* X:\Windows\System32\comdlg32.dll 版本号？

如果是 64 位：

* X:\Windows\SysWOW64\kernel32.dll 版本号？
* X:\Windows\SysWOW64\KernelBase.dll 版本号？
* X:\Windows\SysWOW64\comdlg32.dll 版本号？

**Comment by bombless** [comment]
说不定是它自己用了金钱符号拼路径，哈哈

**Comment by taroxd** [comment]
抱歉一直没看到

Win7 64位
kernel32.dll: 6.1.7601.18869
KernelBase.dll: 6.1.7601.18869
comdlg32.dll: 6.1.7601.17514

> 删除 LERegistry.xml 后双击 LEUpdater.exe 即可解决问题。
抱歉，我这里并没有解决问题

**Comment by taroxd** [comment]
win10 中似乎没有问题了
