### ISSUE TITLE
Small problem with RPGMaker games (probably not only)

### ISSUE THREAD

**Issue by AltairPL** [xupefei/Locale-Emulator#76]
First of all, thanks for LE - I just love it, but on to the point...
I've run into small issue with RPGMaker games (all versions) - running them with LE blocks F1 hotkey, which is used to display options window. It also removes additional menu items from window title bar context menu. Attached are screenshots for running the game with and without LE - "Resize/reposition" menu item is added by third party application and is the one I'd really like to see working with LE. Let me know if you need any additional info.

EDIT: sorry, forgot about OS - Windows 7 64-bit

![with_le](https://cloud.githubusercontent.com/assets/11663448/6845540/249e6116-d3b6-11e4-81ca-ea699005725c.png)
![without_le](https://cloud.githubusercontent.com/assets/11663448/6845541/249f303c-d3b6-11e4-8644-cffb19075892.png)

**Comment by xupefei** [comment]
I think this is related to 32/64bit problem.
* Are you using the 64bit version of the tool which can add "Resize/reposition" option?
* Do RPGMaker has a standalone executable for config?

**Comment by AltairPL** [comment]
This app is called Sizer (http://www.brianapps.net/sizer/) - it's FAQ states "There is no official version supports 64 bit Windows, but version 3.4 aims to provide this functionality.", well... it does work, just not with LE.
Executable no, but it seems that it uses DLL for config - changing this dll name in game's ini file from "Japanese" to "English" changes config window to English one (after restart of course).
Hope this helps.

**Comment by xupefei** [comment]
Could you give me a game that can reproduce this issue and also I can download form somewhere?

**Comment by AltairPL** [comment]
I've uploaded basic RPG Maker XP game and English RTP here:
https://mega.co.nz/#F!VRVnjY5Z!OP_hJe8w-mgUOyv-ZF7d9A
I'm pretty sure that English RTP also installs Japanese dll - changing "Library=RGSS104E.dll" line to "Library=RGSS104J.dll" will change in-game config to Japanese.
English RTP's and sample games can be also downloaded at http://www.rpgmakerweb.com/

**Comment by xupefei** [comment]
I have tested on my computer and it seems no problem.
This is what I did:
1) Change `RGSS104E` to `RGSS104J`
2) Run the game with LE.
The Properties item still showing here:
![2u v hkw3 wv zph ddon0](https://cloud.githubusercontent.com/assets/1687847/6886166/4eb970cc-d635-11e4-8848-2313861589e1.png)

**Comment by AltairPL** [comment]
Tried doing things below without success:
- closing every application and disabling anti-virus software;
- changing security settings for LE folder to full access for everyone;
- manually setting OS locale/regional settings to US English (act of desperation);

Also tried MS AppLocale (still lingers from pre-LE days) - F1 key and context menu items are working as intended, but it seems it doesn't use Japanese font names ("ＭＳ ゴシック" for "MS Gothic", etc.) so text in game is not displayed.

Other than that, I don't know what else can be possible cause, or what else I can try to resolve this.

**Comment by xupefei** [comment]
Try copy `RGSS104E.dll` and `RGSS104J.dll` from `System32` to game's folder, also try re-downloading LE and install again.

**Comment by AltairPL** [comment]
Another list of things I tried without success:
- copying `RGSS104x.dll` libraries to game's folder;
- redownloading and reinstalling LE - versions tried so far: 1.3.0.0, 1.4.1.1, 1.4.1.2pre1;
- moving LE installation folder out of `C:\Program Files\` and `C:\` altogether (with uninstall and install);
- running Windows Update to install system updates (some were overdue - reason for late reply);

Since this is an isolated incident, which you can't replicate, maybe it's not worth your time trying to fix it at this time - might as well be some incompatibility with Polish version of Windows (not likely, but possible) or my current Windows installation (most likely, but I won't have the time in the near future to do full OS reinstall).

**Comment by xupefei** [comment]
It should not caused by the language of your OS, but I will try this on computer in my school: some PC there comes with Polish version of Windows 7.

**Comment by AltairPL** [comment]
Just to let you know, problem doesn't exist in version 2.0.1.0.

**Comment by xupefei** [comment]
Good news :)
