### ISSUE TITLE
无法打开「花咲ワークスプリング！」

### ISSUE THREAD

**Issue by Misaka-11037** [xupefei/Locale-Emulator#77]
游戏程序打上了「AlphaROM認証回避Patch」，用LE（无论是否使用管理员权限）打开时均报错。同样的程序使用VNR 内置的LS 能正常启动。

**Comment by Misaka-11037** [comment]
附上出错时生成的dumpfile：
https://mega.co.nz/#!cYs0xQJR!tuYtNOD1_5dYkN-cIgaqDLLdqK89fuZdg-sbUvGeOtY

**Comment by xupefei** [comment]
对于使用 AlphaRom 的游戏，我推荐使用这个：http://azure.kdays.cn/onekeyunlock
