### ISSUE TITLE
Can't open a Game which needs to be run in Japanese...

### ISSUE THREAD

**Issue by 292858476** [xupefei/Locale-Emulator#78]
So I was cleaning my stuffs in mu computer today and I found my old Japanese Game, I remember I have Locale-emulator so I tried to open it, it used to work I knew. But this time it didn't work as usual instead a message saying "startup failed' popped 
![qq 20150415214407](https://cloud.githubusercontent.com/assets/11972295/7174210/a46560d6-e3b8-11e4-8001-8e8c7f4622ca.png)
up and no matter what I tried it just won't work.

Already tried to turn firewall, anti-virus program on my computer off but still won't work.
Already tried to re-download the game AND Locale-emulator still can't work
Already tried to use 1.3, 1.4 version still can't work

Any suggestions?

**Comment by 292858476** [comment]
oh and btw here's my system information
![11323123](https://cloud.githubusercontent.com/assets/11972295/7174228/fdaa73ac-e3b8-11e4-85c6-1fc810f0f3ea.png)

**Comment by 292858476** [comment]
if I just open the game without the emulator it will be in gibberish...don't understand why a sudden the emulator can't work...

**Comment by xupefei** [comment]
I think you should change this cute emoji 
![wo8 l 7xd v4vl4yyxx q 7](https://cloud.githubusercontent.com/assets/1687847/7201422/27a8b70a-e507-11e4-999d-77ba3e8dd5c2.png)
 to some ASCII letters :)

**Comment by 292858476** [comment]
wow it worked! THANK YOU!
