### ISSUE TITLE
求解，0000142错误..

### ISSUE THREAD

**Issue by afendis** [xupefei/Locale-Emulator#79]
这软件非常好用，很久没用了，最近打开出现142错误
---------------------------
Locale Emulator Version 1.4.1.2
---------------------------
Error Number: C0000142

Commands: "D:\オタサーの姫に告ら\オタサーの姫に告られた結果wwwww.eXe" 

Microsoft Windows NT 6.1.7601 Service Pack 1 x86

NTDLL.DLL: 6.1.7600.16385 (win7_rtm.090713-1255)

KERNELBASE.DLL: 6.1.7601.17965 (win7sp1_gdr.121004-0333)

KERNEL32.DLL: 6.1.7601.17965 (win7sp1_gdr.121004-0333)

USER32.DLL: 6.1.7601.17514 (win7sp1_rtm.101119-1850)

GDI32.DLL: 6.1.7601.18577 (win7sp1_gdr.140822-1508)

If you have any antivirus software running, please turn it off and try again.

If you think this error is related to LE itself, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

**Comment by afendis** [comment]
我system32文件夹里面NTDLL.DLL的版本明明是6.1.7601为啥这个对话框显示7600？？？我想重新注册dll也不成功，显示找不到入口点DllRegisterServe

**Comment by xupefei** [comment]
把 ntdll.dll 发上来看看

**Comment by afendis** [comment]
![image](https://cloud.githubusercontent.com/assets/12099161/7333179/0d3eb090-eb97-11e4-919c-ea2776106d51.png)
感谢解答，我不知道怎么上传文件，但是我上传了这个文件的版本截图，版本明明是足够的，我试过从网上下载过其他的ntdll文件（7601的）依然不行，注册时依然会出现前面的问题

**Comment by xupefei** [comment]
你可以把这个 dll 压缩一下，传到百度盘之类的东西上面。

另外，你能把你的进程列表截图发上来吗？一页一页截就好。

**Comment by afendis** [comment]
http://pan.baidu.com/s/1sjt5ilJ
你好，我把dll文件和进程图片都上传到这个压缩包里了

**Comment by xupefei** [comment]
我推荐你进行如下测试：
1）进入安全模式，把这个 exe 拖到 LEProc.exe 上，看能否运行。
2）卸载 360 和 支付宝控件，再次测试。

**Comment by afendis** [comment]
是让我把dll拖到LEProe.exe吗？我进程里没有LEProc啊

**Comment by xupefei** [comment]
进入安全模式，把 オタサーの姫に告られた結果wwwww.eXe 拖到 LE 安装目录下的 LEProc.exe 上。

**Comment by afendis** [comment]
还是不行，guji

**Comment by xupefei** [comment]
解决了？能回复一下如何搞定的么？

**Comment by afendis** [comment]
并没有。。估计我电脑有什么顽疾吧，暂时下了个NELTA用，不过确实没有LE方便
