### ISSUE TITLE
LiveMaker games do not work

### ISSUE THREAD

**Issue by reyaz006** [xupefei/Locale-Emulator#80]
Like without any locale emulation, most LiveMaker games crash with 0x0eedfade exception at some point.

Ntlea fails the same way.
Ntleas build 44 works fine (although some games rarely become unresponsive randomly).

Using latest version of Locale-Emulator, under 8.1 x64.

**Comment by xupefei** [comment]
All resources of LiveMaker are named with some Japanese characters, so it may caouse problem if you install/extract them without using LE. Please try to install/extract the game with LE, if problem persists, please leave the name of the game and LE version number here.

**Comment by reyaz006** [comment]
I always make sure the game files do not have issues before testing.

If you want an example, here it is:
http://www.dlsite.com/ecchi-eng/work/=/product_id/RE117030.html
- download trial version, extract.
- rename .exe to "game.exe", run with Locale-Emulator.
- main menu loads, then it crashes.

Using Locale-Emulator v1.4.1.2.pre2.2.

**Comment by xupefei** [comment]
Hello, I have tried the game and it works correctly on my Windows 8.1 x64.
This is what I have done:
1) Extract the game
2) Change folder name to some english letters
3) Change .exe to game.exe
4) Run it with LE.

Please make sure you have installed all updates (including optional ones) from Windows Update, because this is sometimes the reason of this kind of problem.

**Comment by reyaz006** [comment]
I believe if this is an issue with not having most recent updates, then it's a poor design choice to only support those updates. As I said, **Ntleas** (which is almost 1 year old now) works fine with this game, on my system which was fully updated around half-year ago.

Here is the message box:
<pre>---------------------------
Locale Emulator Version 1.4.1.2
---------------------------
Error Number: 0

Commands: SYSTEM_REPORT



Microsoft Windows NT 6.2.9200.0 x64

NTDLL.DLL: 6.3.9600.17031 (winblue_gdr.140221-1952)

KERNELBASE.DLL: 6.3.9600.17238 (winblue_gdr.140723-2018)

KERNEL32.DLL: 6.3.9600.17031 (winblue_gdr.140221-1952)

USER32.DLL: 6.3.9600.16384 (winblue_rtm.130821-1623)

GDI32.DLL: 6.3.9600.17415 (winblue_r4.141028-1500)



If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.





You can press CTRL+C to copy this message to your clipboard.


---------------------------
ОК   
---------------------------</pre>
Still, I think something might be missing in your implementation. Seeing how it performs exactly like it was launched without any locale emulation, it seems to be a good evidence. If there are any debug builds, I'd try to test it and provide the info. Otherwise, I'll get back to this issue when I'm able to install latest updates to my OS.

**Comment by xupefei** [comment]
Thanks for the reply. It seems your `KERNELBASE.DLL` is newer than mine. Could you upload this file to one file-sharing site?

LE use a different (more under-hood) hooking method than NTLEA and NTLEAS, which is depend some [un-documented APIs](http://blogs.technet.com/b/stefan_gossner/archive/2005/07/27/undocumented-api-part1.aspx), and may change along with system updates. This is the reason why LE is depend on DLL versions, and can support more games, even applications, than those old solutions.

Yes, there is a debug version of this DLL, you can find it at https://mega.co.nz/#F!QYlWRDYK!SZngRnKE1RMKlvCQJGcQBg.
To use this DLL, please rename and replace the old one, and then use LE to run the game __AS ADMIN__. Then several `.txt` files will appears in `C:\`. You can paste their content here.

So as summary, please (1) upload your `KERNELBASE.DLL` somewhere and (2) paste here the logs.

thanks.

**Comment by reyaz006** [comment]
>LE use a different (more under-hood) hooking method than NTLEA and NTLEAS, which is depend some un-documented APIs, and may change along with system updates.

So any future OS update may break this tool. Sounds bad to me.

Here is my SysWOW64\KernelBase.dll: https://www.sendspace.com/file/qgba0a
Not only it has a different version than reported by LEProc.exe (I think it reports version of my KernelBase.dll.mui instead), but it may be different for each OS version with different languages. I won't be surprised if this can create even more compatibility issues.

Debug logs:
00003758_log.txt:
<pre>Zinit leb D:\Program Files (x86)\Tools\Locale Emulator\LocaleEmulator.dll
reset nls
inst hp: 00000000
hook ntdll
init 00000000
init ret
hook k32</pre>
00003838_log.txt:
<pre>Zinit leb D:\Program Files (x86)\Tools\Locale Emulator\LocaleEmulator.dll
reset nls
inst hp: 00000000
hook ntdll
init 00000000
init ret
create proc
create proc 00000000
AllocVirtualMemoryEx: 00000000
LocalSelfShadow: 00000000
WriteMemory: 00000000
ReadMemory: 00000000
ooxxAddress: 776376E0
WriteProtectMemory: 00000000
inject 00000000</pre>

**Comment by xupefei** [comment]
Everything looks okay in these logs.
Is there any .dmp files exist after the game crashed? If there is, could you upload it somewhere?

**Comment by reyaz006** [comment]
Yes, .dmp file is being created. Here https://www.sendspace.com/file/qvbos6

**Comment by xupefei** [comment]
Thanks for the dump file.
Your issue may related to the system font `MS Gothic`.
Can you check your `C:\Windows\Fonts` for a font named `MS Gothic` or `ＭＳ ゴシック`?

**Comment by reyaz006** [comment]
Checked and this font exists in my system:
msgothic.ttc
v5.10
9 209 540 bytes

I see that Notepad does not display that font in the config list but Word does. Other than that, I don't see a problem with it.

**Comment by xupefei** [comment]
LiveMaker game use some stupid code to check system fonts.

Is there also a font named `ＭＳ  Ｐゴシック`?
If so, try go to `Control Panel\Appearance and Personalization\Fonts\Font settings` and uncheck "Hide font based on language settings", Then try again. If it still does not work, sorry there is nothing more I can help...

**Comment by reyaz006** [comment]
>Is there also a font named  ＭＳ Ｐゴシック ?

No, there is no such font in my system. Of if there is, I have no idea how to check that since it doesn't come up after search in Fonts.

>If so, try go to  Control Panel\Appearance and Personalization\Fonts\Font settings  and uncheck "Hide font based on language settings", Then try again.

Done and it's still all the same.

I guess then Locale-Emulator is quite dependent on the environment. Perhaps it only works fine on OS with certain language packs.

I remember seeing some blog article on LiveMaker fonts problem and 0x0eedfade expection, where author was able to fix that on runtime in OllyDbg, but for whatever reason I could not understand it even with translation (it was japanese or chinese I think), and now the whole blog is down so I can't even ask anyone to check it.

If it's not difficult, can you at least describe the problem with how LiveMaker handles fonts and where it fails? I can do basic debugging with OllyDbg too.

**Comment by xupefei** [comment]
> I guess then Locale-Emulator is quite dependent on the environment. Perhaps it only works fine on OS with certain language packs.
In fact no, LE is running good on Chinese, Japanese, Korean, Russian, English, even Polish windows OS.

> No, there is no such font in my system.
This should be the reason. Could you try install these two fonts, if a notify comes up asking the font is already exist, choose "Overwrite".
https://filetea.me/default/#t1sh1ViuxQURMOuzWmskGUAmw
https://filetea.me/default/#t1shCdci2j9Sm6RSnYkKwR3bg

**Comment by reyaz006** [comment]
"Not found" for both links.

**Comment by xupefei** [comment]
New link: https://infotomb.com/4ozfo

**Comment by reyaz006** [comment]
Ok I tried that and it's all the same. In fact, my versions of those fonts were exactly same.

**Comment by xupefei** [comment]
Sorry, I have no idea why LE does not on your PC because I can't reproduce the problem. You may try another locale emulation software, or make a fresh installation of OS then try again.

**Comment by reyaz006** [comment]
LE works actually, it's just that it can't emulate everything properly. I had same problems with LiveMaker games on first version of NTLEA.

My guess is the OS locale afterall. I (and you) may not have time to check this by hand for now. But when you meet problems in future - remember to always check the OS locale. Because it's possible that only OS of same locale that you have would help some people with certain cases.

**Comment by xupefei** [comment]
LiveMaker game has been tested running on my own English Win8.1, as well as many Chinese/Japanese/Korean/Russian OSs.

I still believe your problem is unique because of your system fonts are somehow corrupted or some apps are preventing LE from hacking into system fonts enumerations. This is the reason why I suggest you do a clean install of OS.

**Comment by reyaz006** [comment]
Tried that.
1.1.1.0 works
1.1.1.1 works
1.2.0.0 doesn't work

**Comment by xupefei** [comment]
Thanks for the response.

[Here](http://www.filedropper.com/fonts_5) is a small tool which will print all your system fonts in a TXT file. Please, try run it 
1) Directly
2) With LE 1.1.1.1
3) With LE 1.2.0.0
Then you can paste the output .txt files to for example Pastebin, and inform me the links.

**Comment by reyaz006** [comment]
1) directly http://pastebin.com/sjM0bcMR
2) 1.1.1.1 http://pastebin.com/mMhTkVzi
3) 1.2.0.0 http://pastebin.com/NQy3xhDm

Apparetly there is no difference between 1.1.1.1 and 1.2.0.0.

I still advise you to check the code differences between these versions, as they appear exactly the same, according to a diff app. Yet the binaries are different.

Also tried the latest 2.0.1.0 - issue is still there.

**Comment by MakiseKurisu** [comment]
> I remember seeing some blog article on LiveMaker fonts problem and 0x0eedfade expection, where author was able to fix that on runtime in OllyDbg, but for whatever reason I could not understand it even with translation (it was japanese or chinese I think), and now the whole blog is down so I can't even ask anyone to check it.

That's probably me, and you know what? Even I have the same issue. I'm running Windows 10 and those LiveMaker games are broken again.

However, I believe the problem is about how Windows implement its API. The game engine must go through a different routine to get FaceName in Windows 10 now. In my homemade locale emulator, I hooked EnumFontFamExFilterW function. I bet it doesn't get called.

I'll take a look at it in the next few days, for I have a new game and I'd like to play it.

**Comment by MakiseKurisu** [comment]
A quick update.

I started 銭湯内でのあるある ～もくもくムクムクよくじょう編～ with Locale Emulator then attached it with Ollydbg.

At FC96E it tried to find the font but cannot find it.

At FC979 it pushed a help string into ecx: 標準フォントがインストールされていません, or Standard font is not installed.

At FC98A it threw out the infamous 0EEDFADE error.

**Comment by MakiseKurisu** [comment]
LOL. You would wonder why the function cannot find the font. Well because the font is not there! I followed the function call at FC96E and double check the font it's looking for. Yes the good old MS ゴシック(Gothic). However in Windows 10 this font doesn't come as default, and that's why it cannot found the font.

A new Japanese font is shipped with Windows 10 and it's called Yu Gothic UI. Maybe remap to this font when you see it's Windows 10 and you cannot find Gothic?

To install MS ゴシック, follow the instruction [here](http://forums.fuwanovel.net/topic/11197-windows-10-kamidori-alchemy-meister/).

With that being said, Locale Emulator is working correctly in Windows 10 Build 10565. So you should check your own system to see if it has the font above.

**Comment by Spaghettiandmeatballs** [comment]
I got the Livemaker engine working with the locale emulator on win10. I already had the additional Asian fonts installed, all I did was go to "Control Panel\All Control Panel Items\Language" then "Change, date, time, number formats" and under the "Administrative" tab I changed the "Locale for non-Unicode programs" to Japan, then the Livenovel サンプルゲーム「GTE・SP」 ver.08.05.12 worked perfectly with locale emulator. http://www.livemaker.net/download/lib/.

**Comment by reyaz006** [comment]
My problem is still not solved.

The font is installed in my system under the name **msgothic.ttc**. It's a collection of 3 Gothic fonts and it was installed as a default system component. The OS does not even allow to remove it, saying it's protected. I found the TTF version and installed it too just in case, but it did not help. (however after that the exception thrown by the games is 0x00000000 instead of 0x0eedfade)

As *MakiseKurisu* said, the engine tries to find **MS ゴシック** font, but it is displayed as **MS Gothic** in most apps. Locale-Emulator is supposed to make system functions process **MS ゴシック** as **MS Gothic**, but it fails to do so on my system since v1.2.0.0.

I tried to look at the source code but discovered that source code for <code>LoaderDll.dll</code> and <code>LocaleEmulator.dll</code> is nowhere to be found. Neither <code>ゴシック</code> nor <code>Gothic</code> are mentioned in the rest of the repository.

Advice from *MakiseKurisu* to install "Japanese Supplemental Fonts" is specifically for Windows 10, while I have Windows 8.1. And advice from *xupefei* to reinstall the whole OS from scratch because of corrupted system fonts does not make much sense.

How else can I debug the problem?

**Comment by xupefei** [comment]
I am sorry guys, now I am only focus on Windows 10 OS because it cost a lot
time to debug issues under several OSs. Another information is I have now
open-sourced the source code of core Dlls so you may use it to address and
fix your problems. It is available at
https://github.com/xupefei/Locale-Emulator-Core. It is under LGPL so feel
free to modify it.

Thanks!

**Comment by reyaz006** [comment]
I've done a bit more of debugging and found out the following:

1. The problem seems to start in <code>EnumFontsA</code>. When the game calls it for the first time, the output data array does not contain <code>ＭＳ ゴシック</code>, while it contains some other stuff like <code>ＤＦ極太ゴシック体</code>. When the game is launched through **Ntlea**, it properly returns the whole family of <code>ＭＳ ゴシック</code>, without <code>ＤＦ極太ゴシック体</code>. When launched without any locale emulation tool, the array does not contain any <code>ゴシック</code> font at all.

2. The <code>fonts.exe</code> application mentioned previously by *xupefei* likely can not be considered a proper test case. Neither <code>EnumFontsA</code> nor <code>EnumFontsW</code> got executed when it is launched.

**Comment by Spaghettiandmeatballs** [comment]
The problem isn't the fonts, I uninstalled all the mentioned fonts and the [http://www.livemaker.net/files/gtesp080512.exe](Sample game "GTE · SP") still worked, however some games may require the additional fonts. 

Livenovel is non-Unicode, change your unicode region http://superuser.com/questions/497857/how-to-change-language-for-non-unicode-programs-in-windows-8 this applies to win8 and win10

**Comment by reyaz006** [comment]
@Spaghettiandmeatballs,
your suggestion about changing *system locale* OS-wide kills the whole purpose of locale emulation software. As I already said, **Ntlea** works with such games (it may have other issues, but games at least work).

The **gtesp080512.exe** you mentioned works for me too, without any kind of emulation (*and* with my system locale set to non-Japanese). The text becomes a mess, but the game does not crash. It's using the old version of LiveMaker engine, and there is something different in its font initializing procedure, I believe. Here is a rough explanation based on my brief observation:

Older LiveMaker games, **gtesp080512.exe** as example:
- on engine start: do nothing about fonts.
- on game start: ask <code>EnumFontsA</code> to prepare the <code>ＭＳ ゴシック</code> font specifically. *This action seems to handle the font successfully, albeit with wrong codepage set OS-wide the text becomes garbage.*

Newer LiveMaker games:
- on engine start: ask <code>EnumFontsA</code> to list/prepare all the fonts available in the system. *The EEDFADE exception code can be seen in the debugger at this point already, but the engine is still working if the game doesn't try to use the font yet. This is the exact problematic place where Locale-Emulator fails to do its work properly on my system.*
- on game start: try to find <code>ＭＳ ゴシック</code> in the list and use it. *<code>EnumFontsA</code> api is not being called at this point. The case where this font was not found is not being properly handled, thus the whole engine crashes.*

**Comment by xupefei** [comment]
Could you following the execution into LocaleEmulator.dll and see what's happened? You can compile the dll by yourself in order to get LocaleEmulator.pdb which may be a help for you.

**Comment by reyaz006** [comment]
I will try that later.

Still, do you have some kind of history of changes from 1.1.1.1 to 1.2.0.0 in the code? If the Locale-Emulator-Core was on github from the start, we could easily find what's wrong.

**Comment by xupefei** [comment]
In ver.1111 we use slow `fms.dll` to get the font names, while in 1200 it has been abandoned.
You may focuses at https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L492.

**Comment by xupefei** [comment]
Please check here: https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L314
This is where we "remove duplicate localized font names."

**Comment by reyaz006** [comment]
My observation:

1. The game executes the <code>EnumFontsA</code> with *pFaceName = NULL*. (might be not important)

2. This leads to <code>FaceName = nullptr</code> [here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L628)

3. The bad stuff happens [here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L314)
<code>if (NT_FAILED(Status) || wcsicmp(FaceName.Buffer, AdjustData->EnumLogFontEx->elfLogFont.lfFaceName) != 0)</code>
The <code>FaceName.Buffer</code> is always <code>MS Gothic</code> by default (maybe because of [this](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/LocaleEmulator.h#L222))
This means that first processed font will always fail with <code>STATUS_CONTEXT_MISMATCH</code> [here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L315). In reality, this happens with many fonts, not just first one. Probably because <code>FaceName</code> is not getting updated when needed. Otherwise, I don't see why this particular <code>wcsicmp</code> has to fail so many times.

I'm having a difficult time trying to understand this line. Here are the logged values of <code>FaceName.Buffer</code> when the engine first calls <code>EnumFontsA</code>: http://pastebin.com/p1DWZa3u
I imagine the duplicate check shouldn't give such results.

Using OllyDbg, I've made the mentioned <code>wcsicmp</code> to always return 0 and my problem was fixed completely.

What do you think?

**Comment by xupefei** [comment]
Could you print the log of values of:
1) FaceName.Buffer
2) AdjustData->EnumLogFontEx->elfLogFont.lfFaceName


And more, what is your 
1) Non-Unicode codepage
2) UI language
3) ![image](https://cloud.githubusercontent.com/assets/1687847/10642536/c656b6ea-7850-11e5-8c82-b4b385a7775d.png)
4) ![image](https://cloud.githubusercontent.com/assets/1687847/10642566/e3efccbe-7850-11e5-97cd-a59713c7835b.png)

**Comment by reyaz006** [comment]
Here is the log of both values: http://pastebin.com/gCLFKHbJ
[ebp-0c] is <code>FaceName.Buffer</code>
eax is <code>AdjustData->EnumLogFontEx->elfLogFont.lfFaceName</code>

So, the first font it tried to process was "Terminal", and after it found it is different from "MS Gothic", it went <code>STATUS_CONTEXT_MISMATCH</code> and never touched "Terminal" again.

Some eax values did not get properly decoded to text, but they contain valid font names. They contain russian characters, e.g. "Arial Narrow Курсив", which means "Arial Narrow Italic". Not sure how properly they got processed by Locale-Emulator, but I guess it doesn't matter much - you can see the whole thing goes wrong right from the start.

Non-Unicode codepage is Russian and UI language is Russian - both are default for my OS installation.

**Comment by MakiseKurisu** [comment]
@reyaz006 

If you read carefully, this [FaceName](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/LocaleEmulator.h#L222) is a static variable, thus cannot be accessed from outside of its slope (in this case the inline function).

The FaceName is actually defined [here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L288), and initialized [here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L303). So by default it's empty.

Then the function called GetNameRecordFromNameTable to get the font face in OriginalLocaleID. The reason that LiveMaker crashes is due to the face that ["The fonts for many East Asian languages have two typeface names: an English name and a localized name. EnumFonts, EnumFontFamilies, and EnumFontFamiliesEx return the English typeface name if the system locale does not match the language of the font."](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162622(v=vs.85).aspx) So since your PC is Russian, the value in FaceName is either English, or Russian. Now what we need to do is to call GetNameRecordFromNameTable with LocaleID (the one we are emulating) to get Japanese font face we want (or English if it's a Russian font).

However we need to make sure the font we are looking for is what we want. Thus there is a check against AdjustData->EnumLogFontEx->elfLogFont.lfFaceName. AdjustFontDataInternal is only called once by AdjustFontData, and AdjustFontData is only called once by LeEnumFontCallbackW. LeEnumFontCallbackW is called by Windows, thus lfFaceName is returned by Windows following the  rule above and those two should match.

**Comment by xupefei** [comment]
Could you try this new dll?
https://infotomb.com/xnas0

**Comment by reyaz006** [comment]
@MakiseKurisu
Thanks for explanation, however I still can't understand parts of it. I'm rather bad at high-level programming for now, and I don't know how fonts in OS are being handled in detail.

@xupefei
Tried that, still the same crash.

I think I found the real cause, at least it happens earlier than the duplicate check and <code>CreateFontIndirectBypassW</code>. [This line](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L483) may contain the wrong condition.

In debugger, the last condition jump in that section is JE (jump if equal). Checked 1.2.0.0 - JE too. But in 1.1.1.1 it's JNE (jump if not equal). This means that for 1.1.1.1, where [this line](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L486) gets executed, in later versions it does not.

In your test dll I see that you've changed something in that line, but it still does not do the right thing for me. In 2.0.1.0, it compares 2 values, probably
<code>lf->lfCharSet == EnumParam->GlobalData->GetLePeb()->OriginalCharset</code>
, in your test dll you only check if one of the values (not sure which) is 0. My current guess is that for 1.1.1.1 it was
<code>lf->lfCharSet != EnumParam->GlobalData->GetLePeb()->OriginalCharset</code>

When I change JE to JNE in 1.2.0.0 and 2.0.1.0, it works like 1.1.1.1 for me - no crashes. I also tried reversing the condition in your test dll, and it also fixes the problem, but I have no idea if that's the proper way, since the whole line is different.

Now, if there is nothing wrong in that line right now, I can only assume it was a bug that was fixed in 1.2.0.0, and the fact that 1.1.1.1 worked for me was a side-effect of that bug.

**Comment by reyaz006** [comment]
Here are additional logs of <code>wcsicmp</code>.
Same as before, [ebp-0c] is <code>FaceName.Buffer</code> and eax is <code>AdjustData->EnumLogFontEx->elfLogFont.lfFaceName</code>

2.0.1.0 with reversed condition [@here](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L483): http://pastebin.com/RSZ1LuyF
Test dll original: http://pastebin.com/kJaG7EHJ
Test dll with reversed condition at the same line: http://pastebin.com/ZxtzPdHY

**Comment by xupefei** [comment]
please try this.
https://infotomb.com/sgsw6

**Comment by reyaz006** [comment]
It works, no crashes on my test case.

From what I can see in the code, you did exactly that - reversed the condition. So my current <code>wcsicmp</code> log for latest file is 1:1 identical to http://pastebin.com/ZxtzPdHY

Please note the cases where <code>FaceName.Buffer</code> is often equals to "MS Gothic", "MS PGothic" or "MS PMincho" where the other variable contains a completely different name. Seeing how 2.0.1.0 could do far less of such discrepancies, I assumed it should be a better choice. I may be wrong.

**Comment by reyaz006** [comment]
Also, I noticed possible startup speed issues. With 2.0.1.0 it takes around 3 seconds (same if I apply the binary patch from https://github.com/xupefei/Locale-Emulator/issues/80#issuecomment-150161816) for game window to appear, with your first test dll it's around 5 seconds, with your latest test dll it's around 8 seconds. (just for the record, with current Ntlea it's ~1 second.)

Tested on RE117030 trial.

**Comment by xupefei** [comment]
@reyaz006 Hello, could you do one more thing: Log all `lfFaceName` and its `lfCharset` at [this line](https://github.com/xupefei/Locale-Emulator-Core/blob/master/LocaleEmulator/Hooks/Gdi32Hook.cpp#L485)?

**Comment by reyaz006** [comment]
@xupefei
http://pastie.org/private/fot0c5c2jgtduhhksakpq

**Comment by xupefei** [comment]
Can you try this dll? How about the startup speed?
https://infotomb.com/wnbqy

**Comment by reyaz006** [comment]
This is truly impressive. Under 1 second, noticeably faster than Ntlea.

If you still need it, here is the new log from the same place: http://pastie.org/private/w57jssvvz3cuoriugoxea

**Comment by xupefei** [comment]
Version 2.1.0.0 is now released. Thanks to everyone in this thread for the help.
Thank you very much.
