### ISSUE TITLE
Crash when using LE

### ISSUE THREAD

**Issue by unsx** [xupefei/Locale-Emulator#81]
When I use LE to play ハメ撮り実況中継！兄妹初エッチ12時間, it crash.
I run"ハメ撮り実況中継.exe", then it crash.
A file call"ハメ撮り実況中継.1D08F81154588C6.crash.dmp" show up in the folder.
Then I run again, "ハメ撮り実況中継.1D08F82D3FEBC19.crash.dmp"show up
I try some game LE work before, but now have same issues, what's going on?

**Comment by xupefei** [comment]
Please upload the `.dmp` files.

**Comment by unsx** [comment]
http://www.mediafire.com/download/id2oo2gy657bonl/%E3%83%8F%E3%83%A1%E6%92%AE%E3%82%8A%E5%AE%9F%E6%B3%81%E4%B8%AD%E7%B6%99.1D092F5FDA99830.crash.dmp

**Comment by xupefei** [comment]
You have not installed all the system updates from Windows Update. Please install all patches (including optional ones) then try again.

**Comment by unsx** [comment]
Updated, but still not work.

http://www.mediafire.com/download/29rhelnzl51uqcc/%E3%83%8F%E3%83%A1%E6%92%AE%E3%82%8A%E5%AE%9F%E6%B3%81%E4%B8%AD%E7%B6%99.1D093B42B20AD4B.crash.dmp

**Comment by xupefei** [comment]
I downloaded the trial version of this game, it runs with latest LE without problem on my Windows 8.1 x64 OS.

Does the game also crash when running it with double-clicking (without LE)?

**Comment by unsx** [comment]
my windows is 64bit.
double-clicking (without LE) can't start the game, but no dmp show up.

**Comment by xupefei** [comment]
So I think your issue is not related to LE. This game is using Kirikiri
Engine and should at least shows up a window when double-clicking (and yes,
in my test it works in this way). As I know you cannot run it even without
LE, there should be some other applications prevent it from starting up.
Please double check all applications you have installed, or maybe reinstall
OS as the last choice.

**Comment by unsx** [comment]
I double-clicking it, a shows up a window. but the game does not start.
http://www.mediafire.com/view/yixo4pp73vf94x0/1.png#

**Comment by xupefei** [comment]
Path can not contain any non-English letters. Please xhange folder names as
well as file names to something like 123.exe, 123.cf.

**Comment by unsx** [comment]
I rename the path and exe file, still the same.
I try some other game with non-English letters, the LE works. 
And some game is from same company.

**Comment by xupefei** [comment]
Sorry but your case is not related to LE itself, but because the Unicode char conversion error in your OS. So it should not be discussed here.

**Comment by unsx** [comment]
what is Unicode char conversion error ? Would it because I use LE to open two game at the same time? Can I fix it?
