### ISSUE TITLE
Win10 下无法使用 Locale Emulator // Locale Emulator does not work in Windows 10

### ISSUE THREAD

**Issue by mammothrider** [xupefei/Locale-Emulator#82]
Win10 10074， 但在之前版本也存在。

游戏应用程序本身，菜单什么的，确实是日语。但是加载的资源就全都是未转化的乱码了。

该问题未在win8中出现。已试用1.3，1.4.1.2，均不行。

**Comment by Ouroboros** [comment]
https://filetea.me/t1sFXxbzkEHTFyF4UVD9OtzvA

替换这个dll进去试试

**Comment by Ouroboros** [comment]
http://pan.baidu.com/s/199QGY

替换一下这个dll

**Comment by mammothrider** [comment]
反而连游戏都打不开了。有进程，无窗口。KIRIKIRI

**Comment by Ouroboros** [comment]
什么游戏, 系统32还是64

**Comment by mammothrider** [comment]
Win10 64位系统
我所有的KIRIKIRI游戏都打不开，试了一下RPG Maker的都可以，WOLF的不行。
有进程无窗口。

**Comment by lhyqy5** [comment]
我也是一样问题，用Locale-Emulator加载程序的时候感觉很多dll都没有加载，如下图
**不用Locale-Emulator加载的情况**：
![image](https://cloud.githubusercontent.com/assets/132520/7725295/dc28a616-ff2b-11e4-8ac0-2590676f83f8.png)
---
**用Locale-Emulator加载的情况**：
![image](https://cloud.githubusercontent.com/assets/132520/7725306/f397d060-ff2b-11e4-9cf3-dac34498ae24.png)

**Comment by bbs3223474** [comment]
是的，目前Windows10 Build 10130 x64版本也无法运行LE，连游戏里的readme.txt都无法转区，但AppLocale似乎也是同一个现象，使用Windows8兼容性设置LEProc.exe无效，x86版Win10似乎没有这个问题

**Comment by xupefei** [comment]
LE 将在 Windows 10 RTM 发布后与之兼容。

LE will compatible with Windows 10 once when it comes to RTM.

**Comment by bbs3223474** [comment]
很感谢作者的努力。
Appreciate that.

**Comment by xupefei** [comment]
Sloved in v2.0.
