### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by eadmaster** [xupefei/Locale-Emulator#84]
is it possible to run the emulator without installation?
(eg. via commandline invocation)

**Comment by xupefei** [comment]
Yes, but first you need to install on any PC once to get the nessessary DLLs (`LECommonLibrary.dll` and `LEContextMenuHandler.dll`), then copy the folder to another PC as a portable app.

For how to use the command line, some instructions are available via double-clicking on `LEProc.exe`.
