### ISSUE TITLE
运行ヤキモチストリーム失败

### ISSUE THREAD

**Issue by Yurikago** [xupefei/Locale-Emulator#86]
中文版windows 8.1
ヤキモチストリーム
使用的是v1.4.1.2.pre2.3版本
运行时显示：（装载目录）\plugin\check.tpm无法读取
但是转到日区可以正常运行

**Comment by xupefei** [comment]
去掉LE配置里的 “注册表重定向” 再试试看。

**Comment by Yurikago** [comment]
还是不行。
windows的更新也都更过了。

**Comment by xupefei** [comment]
我下载了官方提供的试玩版，一切正常。
游戏目录和游戏 exe 里含有汉字或日语么？有的话，全改成英文字符再试。没有的话，我也不知道为什么了。

**Comment by Yurikago** [comment]
仍然不行，还是一样的提示。
感谢你的努力。

**Comment by Yurikago** [comment]
刚才看了一下别人的评论，我下了v1.0.9.0版本，竟然可以正常运行了。

**Comment by xupefei** [comment]
只能1090？1091版本可用么？
