### ISSUE TITLE
似乎我的win8.1 64位中文兼容不了LE

### ISSUE THREAD

**Issue by yaoxiaozhou** [xupefei/Locale-Emulator#90]
比如彼女のセイイキ这个游戏
![qq 20150712203722](https://cloud.githubusercontent.com/assets/13299540/8637781/fa3b9d9c-28d5-11e5-97f6-e26d3106f271.png)
![qq 20150712203730](https://cloud.githubusercontent.com/assets/13299540/8637785/07e2b020-28d6-11e5-8b12-5d2763e6a7ae.png)
还有其他有的gal游戏转区打不开

**Comment by xupefei** [comment]
It should be solved in ver 2.0.0.2. If you still have this issue please comment here.
