### ISSUE TITLE
求142错误的解决方法

### ISSUE THREAD

**Issue by MyMasterArtoria** [xupefei/Locale-Emulator#91]
Locale Emulator Version 1.4.1.2
---------------------------
Error Number: C0000142

Commands: "C:\Ciel\フォルト！！Ａ\FaultA.exe" 

Microsoft Windows NT 6.1.7601 Service Pack 1 x86

NTDLL.DLL: 6.1.7601.18798

KERNELBASE.DLL: 6.1.7601.18847

KERNEL32.DLL: 6.1.7601.18847

USER32.DLL: 6.1.7601.17514

GDI32.DLL: 6.1.7601.18778

If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.

You can press CTRL+C to copy this message to your clipboard.

---------------------------
确定   
---------------------------

我看了以前相似的帖子，也尝试进入安全模式用LEProc.exe运行，但是并不能解决问题

**Comment by MyMasterArtoria** [comment]
刚安装时可以使用，过了一段时间后，首先是出现no profile ,please run the LEGUI.exe ,运行完LEGUI.exe后就出现142错误

**Comment by xupefei** [comment]
It should be solved in ver 2.0.0.2. If you still have this issue please comment here.
