### ISSUE TITLE
File dialog does not show up

### ISSUE THREAD

**Issue by HYBRID-BEING** [xupefei/Locale-Emulator#94]
Windows 8.1 Single Language (Russian), Grisaia and Kamidori installers (works for Artificial Academy though). Tried two latest pre-release versions of LE.
Pressing "Browse..." button (or whatever it is named) on install directory selection screen does not bring up file dialog, barring me from changing installation directory for Kamidori (Grisaia allowed text input). Installation proceeds as normal.

**Comment by xupefei** [comment]
What happened when using LE with Notepad? Does the save dialog pops up
correctly? You should use 32-bit notepad.exe which located in
Windows\SysWOW64 folder.

**Comment by xupefei** [comment]
It should be solved in ver 2.0.0.2. If you still have this issue please comment here.

**Comment by HYBRID-BEING** [comment]
Sorry for the late response, but i confirm that this is indeed fixed in later versions.
