### ISSUE TITLE
win10找不到LEInstaller.exe

### ISSUE THREAD

**Issue by a420653** [xupefei/Locale-Emulator#95]
![default](https://cloud.githubusercontent.com/assets/13564112/8974331/1bb47cf2-36a3-11e5-9a2d-fce63dac324d.PNG)
如图，是缺少组件吗

**Comment by a420653** [comment]
我只是再用最基本的windows defender

**Comment by xupefei** [comment]
你下载的是源代码，不是现成的工具。
2015年7月30日 上午10:11于 "a420653" <notifications@github.com>写道：

**Comment by a420653** [comment]
那请问要怎样做成工具

**Comment by xupefei** [comment]
github下载页面上有个绿色的按钮，点它。
2015年7月30日 上午10:22于 "a420653" <notifications@github.com>写道：

**Comment by a420653** [comment]
十分感谢，等下喔下好了就自己删帖

**Comment by xupefei** [comment]
错了，有个连接写着 *Locale.Emulator.2.0.0.1.Beta.zip
<https://github.com/xupefei/Locale-Emulator/releases/download/v2.0.0.1.Beta/Locale.Emulator.2.0.0.1.Beta.zip>*
2015年7月30日 上午10:26于 "Paddy Xu" <xupaddy@gmail.com>写道：

**Comment by a420653** [comment]
404了。。。

**Comment by a420653** [comment]
https://github.com/xupefei/Locale-Emulator/archive/v2.0.0.1.Beta.zip
我下载的是这个

**Comment by a420653** [comment]
上面的链接直接另存为解压显示压缩包损坏，我用的360压缩

**Comment by lialosiu** [comment]
翻个墙再下.
2015年7月30日 10:34于 "a420653" <notifications@github.com>写道：

**Comment by a420653** [comment]
大哥可以给我发到freedomsis@vip.qq.com这个邮箱吗，翻墙无力

**Comment by xupefei** [comment]
[image: Inline image 1]

**Comment by xupefei** [comment]
![123](https://cloud.githubusercontent.com/assets/1687847/8975050/cf7e9ed6-36ab-11e5-8945-2267faccc212.png)

**Comment by a420653** [comment]
有看到的版主请删帖吧，突然发现自己不会删。。。顺便，程序直接下下不了的，只有源代码可以下，然后我挂了个在线代理秒下。。。

**Comment by lialosiu** [comment]
这是github不是论坛，并没有删帖的说法www
给close掉吧
2015年7月30日 11:19于 "a420653" <notifications@github.com>写道：

**Comment by lialosiu** [comment]
顺便，因为github的release文件挂在Amazon s3上面，所以部分地区是被墙了下载不能的
2015年7月30日 11:19于 "a420653" <notifications@github.com>写道：

**Comment by a420653** [comment]
原来如此，多谢说明了
