### ISSUE TITLE
希望能够支持64位程序

### ISSUE THREAD

**Issue by tangsimi8** [xupefei/Locale-Emulator#96]
如题，CM3D2都已近开始有64位版本了，期待LE支持。

**Comment by lialosiu** [comment]
cm3d2 +1，我现在用着ntleas来艹cm3d2...
LE负责x86，ntleas复制x64...
期待LE能支持x64
2015年7月30日 11:04于 "tangsimi8" <notifications@github.com>写道：

**Comment by xupefei** [comment]
目前是没什么希望，支持 64 位需要从头开始搞，花费的时间多，使用范围窄，不值得。

**Comment by adasqg** [comment]
如果能增加支持64位就完美了
