### ISSUE TITLE
Cannot run Locale-Emulator after install Symantec Endpoint Protection 12.1.6.1

### ISSUE THREAD

**Issue by ming21788** [xupefei/Locale-Emulator#98]
Environment: Windows 10 Pro
Antivirus: Symantec Endpoint Protection 12.1.6.1

Issue:
Even disable the Symantec Endpoint Protection still cannot run the Locale-Emulator program.

![0150801002440](https://cloud.githubusercontent.com/assets/13590776/9011971/c4c80ba6-37e3-11e5-986a-de033ed98c2e.png)

**Comment by ming21788** [comment]
Upgraded to Symantec Endpoint Protection 12.1.6 MP1a Build number: 12.1.6318.6100 still occur same error. Any idea? Thanks

---------------------------
Locale Emulator Version 2.0.0.2
---------------------------
Error Number: C0000142
Commands: "C:\WINDOWS\system32\NOTEPAD.EXE" C:\Users\DarrenLo\Desktop\新文字文件.txt

Microsoft Windows NT 6.2.9200.0 x64
NTDLL.DLL: 6.2.10240.16392
KERNELBASE.DLL: 6.2.10240.16384
KERNEL32.DLL: 6.2.10240.16384
USER32.DLL: 6.2.10240.16384
GDI32.DLL: 6.2.10240.16390

If you have any antivirus software running, please turn it off and try again.
If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.
If you have tried all above but none of them works, feel free to submit an issue at
https://github.com/xupefei/Locale-Emulator/issues.


You can press CTRL+C to copy this message to your clipboard.

---------------------------
確定   
---------------------------

**Comment by xupefei** [comment]
Sorry but this issue can not be solved at the LE side. Please consider reporting this issue to Symantec , or turning off the protection or changing to another security software.
